In [1]:
import pandas as pd

df = pd.read_excel(
    "WLS Data.xlsx",
    sheet_name="Worksheet Final",
    keep_default_na=False
)

print(df.columns)

Index(['Bloomberg Title', 'Ticker', 'Exchange Code', 'Equity Exchange Name',
       'MIC', 'Operating MIC', 'MIC Exchange Name', 'Security Type', 'Name',
       'ISO Country', 'Weight', 'Shares', 'Price'],
      dtype='object')

In [2]:
# Preserve all distinct Bloomberg ticker + MIC combinations
listings = (
    df[["Ticker", "MIC"]]
    .assign(
        Ticker=lambda x: x["Ticker"].astype(str).str.strip(),
        MIC=lambda x: x["MIC"].astype(str).str.strip()
    )
)

listings = listings[
    listings["Ticker"].ne("") & listings["MIC"].ne("")
].drop_duplicates(subset=["Ticker", "MIC"])

# Keep a list of ticker strings for code that expects one
tickers = listings["Ticker"].tolist()

print(f"Number of listings: {len(listings):,}")
print(f"Number of ticker entries: {len(tickers):,}")
print(tickers[:10])

Number of listings: 10,420
Number of ticker entries: 10,420
['NVDA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', '2330', 'AVGO', 'GOOG', 'META', 'TSLA']

In [3]:
mic_to_suffix = {
    # United States
    'XNYS': '', 'XNGS': '', 'XNMS': '', 'XNCM': '', 'XASE': '', 'BATS': '',

    # Asia
    'XTKS': '.T',
    'XNSE': '.NS', 'XBOM': '.BO',
    'XSSC': '.SS', 'XSEC': '.SZ',
    'XHKG': '.HK',
    'ROCO': '.TW', 'XTAI': '.TW',  # Corrected Taiwan suffix
    'XKRX': '.KS', 'XKOS': '.KQ',
    'XIDX': '.JK',
    'XKLS': '.KL',
    'XSES': '.SI',
    'XBKK': '.BK',
    'XPHS': '.PS',

    # Europe
    'XLON': '.L',
    'XSWX': '.SW',
    'XETR': '.DE',
    'XPAR': '.PA',
    'XAMS': '.AS',
    'XSTO': '.ST',
    'XOSL': '.OL',
    'XCSE': '.CO',
    'XHEL': '.HE',
    'XATH': '.AT',
    'XWAR': '.WA',
    'XBRU': '.BR',
    'XWBO': '.VI',
    'XLIS': '.LS',
    'XDUB': '.IR',
    'MTAA': '.MI',

    # Americas
    'XTSE': '.TO',
    'XASX': '.AX',
    'XJSE': '.JO',
    'XSGO': '.SN',
    'XMEX': '.MX',
    'XBOG': '.CL',

    # Middle East and Africa
    'XSAU': '.SR',
    'XTAE': '.TA',
    'XIST': '.IS',
    'XDFM': '.AE',
    'XADS': '.AE',
    'XCAI': '.CA',
    'XKUW': '.KW',
    'DSMD': '.QA',
}

swedish_share_class_tickers = {
    'INVEB', 'ATCOA', 'VOLVB', 'SWEDA', 'ASSAB',
    'SEBA', 'ATCOB', 'ERICB', 'INVEA', 'SHBA',
    'HEXAB', 'SAABB', 'EPIA', 'SECUB', 'LIFCOB',
    'TRELB', 'ADDTB', 'TEL2B', 'SKFB',
    'SKAB', 'EPIB', 'SSABB', 'NIBEB', 'HMB',
    'ESSITYB', 'INDUC', 'BEIJB', 'SCAB',
    'GETIB', 'SECTB', 'SAGAD', 'WALLB', 'ELUXB',
    'NCCB', 'ENGCONB', 'CREDA', 'COREB', 'INTEAD',
    'BALDB', 'EMILB', 'MMGRB', 'BIOAB', 'RATOB',
    'NOLAB', 'PEABB', 'BILIA', 'INDUA', 'VOLVA',
    'SHBB', 'PNDXB', 'LATOB', 'SVEAFB', 'NEWAB',
    'HOLMB', 'BETSB', 'VITB', 'HUSQB', 'MTGB',
    'SSABA', 'INTEAB', 'SDIPB', 'ALLIGOB', 'SBBB',
    'RAYB', 'SAGAB', 'LAGRB', 'EMBRACB', 'SWECB',
    'ALIFB', 'LOGIB', 'ARJOB', 'CLAB', 'MCOVB',
    'LUNDB', 'FPARA', 'SEBC', 'BEIAB', 'STEFB',
    'ATRLJB', 'HUFVA', 'VOLCARB', 'BIOGB', 'EKTAB',
    'HPOLB', 'STORYB', 'VBGB', 'OEMB', 'KINVB',
    'SVOLB', 'BERGB', 'ANODB', 'TRUEB', 'PLAZB',
    'EPROB', 'SKISB', 'SLPB', 'CLASB'
}

danish_share_class_tickers = {
    'ALKB', 'AMBUB', 'CARLB', 'COLOB',
    'HLUNA', 'HLUNB', 'MAERSKA', 'MAERSKB',
    'NOVOB', 'NSISB', 'PAALB', 'ROCKB'
}

ticker_transformations = {
    # Sweden: add a hyphen for verified share-class tickers (e.g. INVEB -> INVE-B)
    'XSTO': lambda ticker: (
        ticker[:-1] + '-' + ticker[-1]
        if ticker in swedish_share_class_tickers
        else ticker
    ),

    # Denmark: add a hyphen for verified share-class tickers (e.g. NOVOB -> NOVO-B)
    'XCSE': lambda ticker: (
        ticker[:-1] + '-' + ticker[-1]
        if ticker in danish_share_class_tickers
        else ticker
    ),
    
    # Hong Kong: 700 -> 0700
    'XHKG': lambda ticker: ticker.zfill(4),

    # UK: remove trailing hyphen (e.g. AV- -> AV)
    'XLON': lambda ticker: (
        ticker[:-1] if ticker.endswith('-') else ticker
    ),

    # Mexico: remove a trailing asterisk (e.g. PE&OLES* -> PE&OLES)
    'XMEX': lambda ticker: (
        ticker[:-1] if ticker.endswith('*') else ticker
    ),
}

# Bloomberg-to-Yahoo ticker overrides for symbols that differ
ticker_overrides = {
    # India
    'HDFCB': 'HDFCBANK.NS',
    'ICICIBC': 'ICICIBANK.NS',
    'BHARTI': 'BHARTIARTL.NS',
    'AXSB': 'AXISBANK.NS',
    'INFO': 'INFY.NS',
    'BAF': 'BAJFINANCE.NS',
    'MM': 'M&M.NS',
    'SHFL': 'SHRIRAMFIN.NS',
    'SUNP': 'SUNPHARMA.NS',
    'TTAN': 'TITAN.NS',
    'BHE': 'BEL.NS',
    'APNT': 'ASIANPAINT.NS',
    'MSIL': 'MARUTI.NS',
    'UTCEM': 'ULTRACEMCO.NS',
    'DIVI': 'DIVISLAB.NS',
    'ADANIGR': 'ADANIGREEN.NS',
    'MAXHEALT': 'MAXHEALTH.NS',
    'MOTHERSO': 'MOTHERSON.NS',
    'BJAUT': 'BAJAJ-AUTO.NS',
    'TVSL': 'TVSMOTOR.NS',
    'LAURUS': 'LAURUSLABS.NS',
    'ADSEZ': 'ADANIPORTS.NS',
    'HUVR': 'HINDUNILVR.NS',
    'TATA': 'TATASTEEL.NS',
    'ADANI': 'ADANIPOWER.NS',
    'HNDL': 'HINDALCO.NS',
    'JSTL': 'JSWSTEEL.NS',
    'ADE': 'ADANIENT.NS',
    'PWGR': 'POWERGRID.NS',
    'BJFIN': 'BAJAJFINSV.NS',
    'EIM': 'EICHERMOT.NS',
    'HCLT': 'HCLTECH.NS',
    'HNAL': 'HAL.NS',
    'NEST': 'NESTLEIND.NS',
    'APHS': 'APOLLOHOSP.NS',
    'COAL': 'COALINDIA.NS',
    'FB': 'FEDERALBNK.NS',
    'CIFC': 'CHOLAFIN.NS',
    'KKC': 'CUMMINSIND.NS',
    'IH': 'INDHOTEL.NS',
    'HMCL': 'HEROMOTOCO.NS',
    'SRCM': 'SHREECEM.NS',
    'IDFCFB': 'IDFCFIRSTB.NS',
    'AL': 'ASHOKLEY.NS',
    'PSYS': 'PERSISTENT.NS',
    'TATACONS': 'TATACONSUM.NS',
    'YES': 'YESBANK.NS',
    'GVTD': 'GVT&D.NS',
    'BRIT': 'BRITANNIA.NS',
    'TPWR': 'TATAPOWER.NS',
    'IIB': 'INDUSINDBK.NS',
    'BHFC': 'BHARATFORG.NS',
    'SOIL': 'SOLARINDS.NS',
    'DRRD': 'DRREDDY.NS',
    'INDUSTOW': 'INDUSTOWER.NS',
    'INFOE': 'NAUKRI.NS',
    'BJHI': 'BAJAJHLDNG.NS',
    'LPC': 'LUPIN.NS',
    'SUEL': 'SUZLON.NS',
    'POWF': 'PFC.NS',
    'ARBP': 'AUROPHARMA.NS',
    'DLFU': 'DLF.NS',
    'WPRO': 'WIPRO.NS',
    'ADANIENS': 'ADANIENSOL.NS',
    'JINDALST': 'JINDALSTEL.NS',
    'PIDI': 'PIDILITIND.NS',
    'POWERIND': 'POWERINDIA.NS',
    'MRCO': 'MARICO.NS',
    'PHNX': 'PHOENIXLTD.NS',
    'POLICYBZ': 'POLICYBZR.NS',
    'IOCL': 'IOC.NS',
    'APAT': 'APLAPOLLO.NS',
    'BOB': 'BANKBARODA.NS',
    'FORH': 'FORTIS.NS',
    'MAXF': 'MFSL.NS',
    'RECL': 'RECLTD.NS',
    'ABCAP': 'ABCAPITAL.NS',
    'RDCK': 'RADICO.NS',
    'GNP': 'GLENMARK.NS',
    'HPCL': 'HINDPETRO.NS',
    'GCPL': 'GODREJCP.NS',
    'ATHERENE': 'ATHERENERG.NS',
    'BOS': 'BOSCHLTD.NS',
    'SIEM': 'SIEMENS.NS',
    'APR': 'APARINDS.NS',
    'GMRAIRPO': 'GMRAIRPORT.NS',
    'KVB': 'KARURVYSYA.NS',
    'SUF': 'SUNDARMFIN.NS',
    'WLCO': 'WELCORP.NS',
    'MUTH': 'MUTHOOTFIN.NS',
    'NACL': 'NATIONALUM.NS',
    'HMFC': 'HFCL.NS',
    'NFIL': 'NAVINFLUOR.NS',
    'UPLL': 'UPL.NS',
    'INBK': 'INDIANB.NS',
    'KEII': 'KEI.NS',
    'MPHL': 'MPHASIS.NS',
    'UNBK': 'UNIONBANK.NS',
    'JDSL': 'JSL.NS',
    'RBK': 'RBLBANK.NS',
    'OINL': 'OIL.NS',
    'REDI': 'REDINGTON.NS',
    'JSW': 'JSWENERGY.NS',
    'BIOS': 'BIOCON.NS',
    'PEPL': 'PRESTIGE.NS',
    'ACEM': 'AMBUJACEM.NS',
    'ZYDUSLIF': 'ZYDUSLIFE.NS',
    'PLNG': 'PETRONET.NS',
    'PIRAMALF': 'PIRAMALFIN.NS',
    'TPW': 'TORNTPOWER.NS',
    'HAVL': 'HAVELLS.NS',
    'VOLT': 'VOLTAS.NS',
    'KALYANKJ': 'KALYANKJIL.NS',
    'SI': 'SUPREMEIND.NS',
    'CLGT': 'COLPAL.NS',
    'CUBK': 'CUB.NS',
    'IPCA': 'IPCALAB.NS',
    'OBER': 'OBEROIRLTY.NS',
    'BLSTR': 'BLUESTARCO.NS',
    'FLUOROCH': 'FLUOROCHEM.NS',
    'ANANDRAT': 'ANANDRATHI.NS',
    'PNBHOUSI': 'PNBHOUSING.NS',
    'DELHIVER': 'DELHIVERY.NS',
    'GPL': 'GODREJPROP.NS',
    'KOEL': 'KIRLOSENG.NS',
    'TCOM': 'TATACOMM.NS',
    'JKCE': 'JKCEMENT.NS',
    'CRIN': 'COROMANDEL.NS',
    'LGEL': 'LGEINDIA.NS',
    'TDPS': 'TDPOWERSYS.NS',
    'JUBI': 'JUBLFOOD.NS',
    'WAAREEEN': 'WAAREEENER.NS',
    'NLL': 'NEULANDLAB.NS',
    'IPRU': 'ICICIPRULI.NS',
    'PIRPHARM': 'PPLPHARMA.NS',
    'NAM': 'NAM-INDIA.NS',
    'WPL': 'WOCKPHARMA.NS',
    'MGFL': 'MANAPPURAM.NS',
    'MOFS': 'MOTILALOFS.NS',
    'EXID': 'EXIDEIND.NS',
    'MMFS': 'M&MFIN.NS',
    'AJP': 'AJANTPHARM.NS',
    'GUJENERG': 'GUJENERGY.NS',
    'CUPD': 'CUPID.NS',
    'APTY': 'APOLLOTYRE.NS',
    'SCHFL': 'SCHAEFFLER.NS',
    'LICHF': 'LICHSGFIN.NS',
    'GESCO': 'GESHIP.NS',
    'BANDHAN': 'BANDHANBNK.NS',
    'ITCHOTEL': 'ITCHOTELS.NS',
    'AIAE': 'AIAENG.NS',
    'POONAWAL': 'POONAWALLA.NS',
    'ASTRA': 'ASTRAL.NS',
    'HSCH': 'HSCL.NS',
    'HCP': 'HINDCOPPER.NS',
    'DLPL': 'LALPATHLAB.NS',
    'CRAFTSMA': 'CRAFTSMAN.NS',
    'JSAW': 'JINDALSAW.NS',
    'CHOLAHLD': 'CHOLAHLDNG.NS',
    'TMX': 'THERMAX.NS',
    'PREMIERE': 'PREMIERENE.NS',
    'DALBHARA': 'DALBHARAT.NS',
    'MAZDOCKS': 'MAZDOCK.NS',
    'BOMH': 'MAHABANK.NS',
    'STARHEAL': 'STARHEALTH.NS',
    'UJJIVANS': 'UJJIVANSFB.NS',
    'KPR': 'KPRMILL.NS',
    'ASTM': 'ASTRAMICRO.NS',
    'USM': 'USHAMART.NS',
    'ELEQ': 'ELGIEQUIP.NS',
    'GRAN': 'GRANULES.NS',
    'KBL': 'KTKBANK.NS',
    'GP': 'GODFRYPHLP.NS',
    'BRGR': 'BERGEPAINT.NS',
    'LIIL': 'LINDEINDIA.NS',
    'BOI': 'BANKINDIA.NS',
    'TMKN': 'TIMKEN.NS',
    'CCRI': 'CONCOR.NS',
    'BHARTIHE': 'BHARTIHEXA.NS',
    'GLXO': 'GLAXO.NS',
    'NARH': 'NH.NS',
    'SAMMAANC': 'SAMMAANCAP.NS',
    'KJC': 'KAJARIACER.NS',
    'TRCL': 'RAMCOCEM.NS',
    'ONESOURC': 'ONESOURCE.NS',
    'ZCVCS': 'ZFCVINDIA.NS',
    'FNXC': 'FINCABLES.NS',
    'DATAPATT': 'DATAPATTNS.NS',
    'HOMEFIRS': 'HOMEFIRST.NS',
    'SLPA': 'SHILPAMED.NS',
    'BRGD': 'BRIGADE.NS',
    'COCHIN': 'COCHINSHIP.NS',
    'GWN': 'GRINDWELL.NS',
    'TELX': 'TATAELXSI.NS',
    'DN': 'DEEPAKNTR.NS',
    'DFPC': 'DEEPAKFERT.NS',
    'VATW': 'WABAG.NS',
    'CYL': 'CYIENT.NS',
    'ARTO': 'AARTIIND.NS',
    'AISG': 'ASAHIINDIA.NS',
    'ATLP': 'ATUL.NS',
    'TATAINVE': 'TATAINVEST.NS',
    'ACMESOLA': 'ACMESOLAR.NS',
    'UBBL': 'UBL.NS',
    'GABR': 'GABRIEL.NS',
    '3M': '3MINDIA.NS',
    'HBLENGIN': 'HBLENGINE.NS',
    'NLC': 'NLCINDIA.NS',
    'SHADOWF': 'SHADOWFAX.NS',
    'LLOYDSEN': 'LLOYDSENGG.NS',
    'ENGR': 'ENGINERSIN.NS',
    'ARCP': 'ANANTRAJ.NS',
    'PATANJAL': 'PATANJALI.NS',
    'FML': 'FORCEMOT.NS',
    'TLNGR': 'TI.NS',
    'TTCH': 'TATACHEM.NS',
    'ARENM': 'ARE&M.NS',
    'BLUESTON': 'BLUESTONE.NS',
    'ARVND': 'ARVIND.NS',
    'CSTRL': 'CASTROLIND.NS',
    'INXW': 'INOXWIND.NS',
    'ECLX': 'ECLERX.NS',
    'EDEL': 'EDELWEISS.NS',
    'BRCM': 'BALRAMCHIN.NS',
    'PCJL': 'PCJEWELLER.NS',
    'SHEP': 'SHAILY.NS',
    'NTCPH': 'NATCOPHARM.NS',
    'VTEX': 'VTL.NS',
    'CCLP': 'CCL.NS',
    'FSOL': 'FSL.NS',
    'JUBLPHAR': 'JUBLPHARMA.NS',
    'VAMP': 'VOLTAMP.NS',
    'ZEN': 'ZENTEC.NS',
    'JPVL': 'JPPOWER.NS',
    'HWA': 'HONAUT.NS',
    'SHYAMMET': 'SHYAMMETL.NS',
    'MRKS': 'MARKSANS.NS',
    'AADHARHF': 'AADHARHFC.NS',
    'EQUITASB': 'EQUITASBNK.NS',
    'CEAT': 'CEATLTD.NS',
    'TRIV': 'TRITURBINE.NS',
    'CREDAG': 'CREDITACC.NS',
    'EID': 'EIDPARRY.NS',
    'SHRIPIST': 'SHRIPISTON.NS',
    'CHMB': 'CHAMBLFERT.NS',
    'WELSPUNL': 'WELSPUNLIV.NS',
    'HTSMF': 'HATSUN.NS',
    'UTIAM': 'UTIAMC.NS',
    'BLACKBUC': 'BLACKBUCK.NS',
    'SYNG': 'SYNGENE.NS',
    'SCHI': 'SUDARSCHEM.NS',
    'ENDU': 'ENDURANCE.NS',
    'WHIRL': 'WHIRLPOOL.NS',
    'CFIS': 'CHOICEIN.NS',
    'RMT': 'RATNAMANI.NS',
    'GRWRHITE': 'GRWRHITECH.NS',
    'PLM': 'POLYMED.NS',
    'HAPPYFOR': 'HAPPYFORGE.NS',
    'CANF': 'CANFINHOME.NS',
    'EIH': 'EIHOTEL.NS',
    'TIME': 'TIMETECHNO.NS',
    'RMKF': 'RKFORGE.NS',
    'ZENT': 'ZENSARTECH.NS',
    'METROHL': 'METROPOLIS.NS',
    'KECI': 'KEC.NS',
    'VGRD': 'VGUARD.NS',
    'GRIL': 'GRAPHITE.NS',
    'RPWR': 'RPOWER.NS',
    'LEMONTRE': 'LEMONTREE.NS',
    'CLPL': 'CAPLIPOINT.NS',
    'SWH': 'JSWHL.NS',
    'JKBK': 'J&KBANK.NS',
    'TJL': 'THANGAMAYL.NS',
    'LMAX': 'LUMAXTECH.NS',
    'SPPT': 'SPLPETRO.NS',
    'MHSC': 'MAHSCOOTER.NS',
    'PFIZ': 'PFIZER.NS',
    'JUBLINGR': 'JUBLINGREA.NS',
    'DCBB': 'DCBBANK.NS',
    'MAHGL': 'MGL.NS',
    'NJCC': 'NCC.NS',
    'DYTC': 'DYNAMATECH.NS',
    'TFCI': 'TFCILTD.NS',
    'KKPC': 'KIRLPNU.NS',
    'ACCE': 'ACE.NS',
    'ZYWL': 'ZYDUSWELL.NS',
    'GODPI': 'GPIL.NS',
    'PRICOL': 'PRICOLLTD.NS',
    'GILL': 'GILLETTE.NS',
    'INMART': 'INDIAMART.NS',
    'RINDL': 'RAIN.NS',
    'INOXINDI': 'INOXINDIA.NS',
    'GPPV': 'GPPL.NS',
    'INDA': 'INTELLECT.NS',
    'PRIF': 'PFOCUS.NS',
    'SIGNATUR': 'SIGNATURE.NS',
    'SEML': 'SARDAEN.NS',
    'ELCN': 'ELECON.NS',
    'BYRCS': 'BAYERCROP.NS',
    'GRAV': 'GRAVITA.NS',
    'GDSP': 'GODREJIND.NS',
    'GMM': 'GMMPFAUDLR.NS',
    'AARTIPHA': 'AARTIPHARM.NS',
    'SARE': 'SAREGAMA.NS',
    'CONCORDB': 'CONCORDBIO.NS',
    'ALPM': 'APLLTD.NS',
    'IBULLSLT': 'IBULLSLTD.NS',
    'SSOF': 'SONATSOFTW.NS',
    'KKB': 'KIRLOSBROS.NS',
    'AEGISVOP': 'AEGISVOPAK.NS',
    'GEXP': 'GOKEX.NS',
    'JKI': 'JKTYRE.NS',
    'CPBI': 'CENTURYPLY.NS',
    'RELG': 'RELIGARE.NS',
    'GMDC': 'GMDCLTD.NS',
    'GTFL': 'GARFIBRES.NS',
    'FNXP': 'FINPIPE.NS',
    'AXET': 'AXISCADES.NS',
    'GPIN': 'GENUSPOWER.NS',
    'CYIENTDL': 'CYIENTDLM.NS',
    'LLOYDSET': 'LLOYDSENT.NS',
    'GMRPUI': 'GMRP&UI.NS',
    'ION': 'IONEXCHANG.NS',
    'VI': 'VESUVIUS.NS',
    'PRJ': 'PRAJIND.NS',
    'JSWCEMEN': 'JSWCEMENT.NS',
    'PWI': 'PRECWIRE.NS',
    'ICNT': 'ICIL.NS',
    'MHS': 'MAHSEAMLES.NS',
    'AGARWALE': 'AGARWALEYE.NS',
    'CBOI': 'CENTRALBK.NS',
    'TXMRE': 'TEXRAIL.NS',
    'SKF': 'SKFINDIA.NS',
    'ELSC': 'ELECTCAST.NS',
    'LGBB': 'LGBBROSLTD.NS',
    'TIMX': 'TIMEX.BO',
    'ARVINDFA': 'ARVINDFASN.NS',
    'EPLL': 'EPL.NS',
    'KNPL': 'KANSAINER.NS',
    'KKF': 'KIRLFER.BO',
    'PTCIN': 'PTC.NS',
    'BECTORS': 'BECTORFOOD.NS',
    'THYROCAR': 'THYROCARE.NS',
    'POWM': 'POWERMECH.NS',
    'BLSIN': 'BLS.NS',
    'BATA': 'BATAINDIA.NS',
    'METROBRA': 'METROBRAND.NS',
    'VO': 'VINATIORGA.NS',
    'KRB': 'KRBL.NS',
    'JKLC': 'JKLAKSHMI.NS',
    'BLIS': 'BLISSGVS.NS',
    'SVLS': 'SUVEN.NS',
    'SUDEEPPH': 'SUDEEPPHRM.NS',
    'KPIG': 'KPIGREEN.NS',
    'NGE': 'JAYNECOIND.NS',
    'GOAGRO': 'GODREJAGRO.NS',
    'INDIASHL': 'INDIASHLTR.NS',
    'JMNA': 'JAMNAAUTO.NS',
    'MAXESTAT': 'MAXESTATES.NS',
    'TIPSMUSI': 'TIPSMUSIC.NS',
    'VREL': 'V2RETAIL.NS',
    'ASKAUTOL': 'ASKAUTOLTD.NS',
    'ASTR': 'ASTRAZEN.NS',
    'TRID': 'TRIDENT.NS',
    'BJH': 'BAJAJHIND.NS',
    'KMC': 'KOVAI.BO',
    'AACL': 'ALKYLAMINE.NS',
    'BDE': 'BLUEDART.NS',
    'DCMS': 'DCMSHRIRAM.NS',
    'BNCO': 'BANCOINDIA.NS',
    'RRW': 'RAMRAT.NS',
    'MAST': 'MASTEK.NS',
    'SKPI': 'SHAKTIPUMP.NS',
    'JYL': 'JYOTHYLAB.NS',
    'NRBBR': 'NRBBEARING.NS',
    'IGSEC': 'ISGEC.NS',
    'HAPPSTMN': 'HAPPSTMNDS.NS',
    'BALUFORG': 'BALUFORGE.NS',
    'BORORENE': 'BORORENEW.NS',
    'ASMN': 'ASHAPURMIN.NS',
    'ICP': 'IOLCP.NS',
    'SANOFICO': 'SANOFI.NS',
    'EUREKAFO': 'EUREKAFORB.NS',
    'ROLEXRIN': 'ROLEXRINGS.NS',
    'FTXC': 'FCL.NS',
    'KNM': 'KENNAMET.NS',
    'INDIGOPN': 'INDIGOPNTS.NS',
    'RAYMONDR': 'RAYMONDREL.NS',
    'GALSURF': 'GALAXYSURF.NS',
    'AVTS': 'AVANTEL.NS',
    'VIP': 'VIPIND.NS',
    'GAEX': 'GAEL.NS',
    'BCORP': 'BIRLACORPN.NS',
    'SYR': 'SURYAROSNI.NS',
    'SANL': 'SANOFI.NS',
    'TRAVELFO': 'TRAVELFOOD.NS',
    'PRSMJ': 'PRSMJOHNSN.NS',
    'GLIN': 'GOODLUCK.NS',
    'RITE': 'RITES.NS',
    'FIEM': 'FIEMIND.NS',
    'FDCLT': 'FDC.NS',
    'MBAP': 'MBAPL.NS',
    'WAREERTL': 'WAAREERTL.NS',
    'GRV': 'GREAVESCOT.NS',
    'OPIL': 'OPTIEMUS.NS',
    'WESL': 'WEBELSOLAR.NS',
    'ORIENTEL': 'ORIENTELEC.NS',
    'INOXGREE': 'INOXGREEN.NS',
    'PARKHOSP': 'PARKHOSPS.NS',
    'SISLTD': 'SHAREINDIA.NS',
    'VIKRAMSO': 'VIKRAMSOLR.NS',
    'TANF': 'TANFACIND.BO',
    'IDEAFORG': 'IDEAFORGE.NS',
    'VRLL': 'VRLLOG.NS',
    'TRPC': 'TCI.NS',
    'SWE': 'SWARAJENG.NS',
    'SHMO': 'SHARDAMOTR.NS',
    'NETM': 'NETWORK18.NS',
    'GLDM': 'GOLDIAM.NS',
    'TRANSRAI': 'TRANSRAILL.NS',
    'UFLX': 'UFLEX.NS',
    'ATLANTAE': 'ATLANTAELE.NS',
    'INNOVACA': 'INNOVACAP.NS',
    'SHRS': 'RENUKA.NS',
    'SUNF': 'SUNFLAG.NS',
    'SPADV': 'SPARC.NS',
    'PCAI': 'PICCADIL.NS',
    'GOLI': 'GULFOILLUB.NS',
    'RTPOW': 'RTNPOWER.NS',
    'PWRL': 'POWERICA.NS',
    'RALI': 'RALLIS.NS',
    'KS': 'KSL.NS',
    'ICEM': 'INDIACEM.NS',
    'AUPS': 'AURIONPRO.NS',
    'RPE': 'RPEL.NS',
    'TTKPT': 'TTKPRESTIG.NS',
    'TTLS': 'TTML.NS',
    'STEC': 'SOTL.NS',
    'SHCR': 'SHARDACROP.NS',
    'VSTT': 'VSTTILLERS.NS',
    'MINF': 'MANINFRA.NS',
    'VDI': 'VADILALIND.NS',
    'KNRC': 'KNRCON.NS',
    'BANSALWI': 'BANSALWIRE.NS',
    'SYIL': 'STYLAMIND.NS',
    'TC': 'THOMASCOOK.NS',
    'AHLU': 'AHLUCONT.NS',
    'SECIS': 'SIS.NS',
    'GRLM': 'GREENLAM.NS',
    'ORCP': 'ORCHPHARMA.NS',
    'JBIL': 'JAIBALAJI.NS',
    'ARTD': 'AARTIDRUGS.NS',
    'REFX': 'REFEX.NS',
    'PNCL': 'PNCINFRA.NS',
    'AGIG': 'AGI.NS',
    'UVC': 'UNIVCABLES.NS',
    'MAPMYIND': 'MAPMYINDIA.NS',
    'RAYMONDL': 'RAYMONDLSL.NS',
    'JUST': 'JUSTDIAL.NS',
    'RLXF': 'RELAXO.NS',
    'SRIN': 'SUNTECK.NS',
    'NIRL': 'NIRLON.BO',
    'GALK': 'GUJALKALI.NS',
    'SUBR': 'SUBROS.NS',
    'WPI': 'WPIL.BO',
    'LATENTVI': 'LATENTVIEW.NS',
    'IPMC': 'INDRAMEDCO.NS',
    'BJE': 'BAJAJELEC.NS',
    'BOSCHHCI': 'BOSCH-HCIL.NS',
    'CHEMPLAS': 'CHEMPLASTS.NS',
    'ASBL': 'ASHOKA.NS',
    'SHREEJIS': 'SHREEJISPG.NS',
    'ORKLAIND': 'ORKLAINDIA.NS',
    'SCTE': 'SHILCTECH.NS',
    'ADVENZY': 'ADVENZYMES.NS',
    'SMARTWOR': 'SMARTWORKS.NS',
    'CAPILLAR': 'CAPILLARY.NS',
    'LUMX': 'LUMAXIND.NS',
    'RUSTOMJE': 'RUSTOMJEE.NS',
    'RPGL': 'RPGLIFE.NS',
    'MPS': 'MPSLTD.NS',
    'VGM': 'VAIBHAVGBL.NS',
    'GANESHHO': 'GANESHHOU.NS',
    'DAGRI': 'DHANUKA.NS',
    'IFBI': 'IFBIND.NS',
    'DPAL': 'DPABHUSHAN.NS',
    'GW': 'GRAUWEIL.BO',
    'RESP': 'RESPONIND.NS',
    'SG': 'SHANTIGEAR.NS',
    'ALOK': 'ALOKINDS.NS',
    'COCKERIL': 'COCKERILL.BO',
    'PACD': 'PACEDIGITK.NS',
    'KALPATAR': 'KALPATARU.NS',
    'MHRL': 'MHRIL.NS',
    'ARTMSL': 'ARTEMISMED.NS',
    'NELI': 'NAVNETEDUL.NS',
    'IGLY': 'INDIAGLYCO.NS',
    'SYML': 'SYMPHONY.NS',
    'DATAMATI': 'DATAMATICS.NS',
    'MIDWESTL': 'MIDWESTLTD.NS',
    'KKIL': 'KIRLOSIND.NS',
    'KPDL': 'KOLTEPATIL.NS',
    'PSPPL': 'PSPPROJECT.NS',
    'RATI': 'RTNINDIA.NS',
    'MUTHOOTM': 'MUTHOOTMF.NS',
    'RSYS': 'RSYSTEMS.NS',
    'SAATVIK': 'SAATVIKGL.NS',
    'DBCL': 'DBCORP.NS',
    'KEKC': 'KKCL.NS',
    'JTEKT': 'JTEKTINDIA.NS',
    'OSWALPUM': 'OSWALPUMPS.NS',
    'SINDHUTR': 'SINDHUTRAD.NS',

    
    # Saudi Arabia
    'RJHI': '1120.SR',
    'ARAMCO': '2222.SR',
    'SNB': '1180.SR',
    'MAADEN': '1211.SR',
    'STC': '7010.SR',
    'ALINMA': '1150.SR',
    'SAFCO': '2020.SR',
    'EEC': '7020.SR',
    'ALMARAI': '2280.SR',
    'RIBL': '1010.SR',
    'SABIC': '2010.SR',
    'ACWA': '2082.SR',
    'BSF': '1050.SR',
    

    # Taiwan — Taipei Exchange
    '5274': '5274.TWO',
    '3105': '3105.TWO',
    '6274': '6274.TWO',
    '3081': '3081.TWO',
    '6488': '6488.TWO',
    '8299': '8299.TWO',
    '6223': '6223.TWO',
    '3529': '3529.TWO',
    '5347': '5347.TWO',

    # UAE
    'EMIRATES': 'EMIRATESNBD.AE',

    # Ireland
    'AIBG': 'A5G.IR',

    # Finland
    'NDA': 'NDA-FI.HE',

    # Malaysia
    'MAY': '1155.KL',
    'PBK': '1295.KL',

    # Singapore
    'DBS': 'D05.SI',
    'OCBC': 'O39.SI',
    'SGX': 'S68.SI',
    'ST': 'Z74.SI',
    'UOB': 'U11.SI',

    # Chile
    'FALAB': 'FALABELLA.SN',

    # Sweden
    'OCTVSDB': 'OCTV-SDB.ST',
    'ASMDEE': 'ASMDEE-B.ST',
}

In [4]:
# Create mapping DataFrame, keeping one row per Bloomberg ticker + MIC
mapping = (
    df[["Ticker", "MIC", "ISO Country", "Name"]]
    .copy()
)

for col in ["Ticker", "MIC", "ISO Country", "Name"]:
    mapping[col] = mapping[col].astype(str).str.strip()

mapping = mapping[
    mapping["Ticker"].ne("") & mapping["MIC"].ne("")
].drop_duplicates(subset=["Ticker", "MIC"]).copy()

# Generate Yahoo Finance ticker and mapping status
def map_ticker(row):
    ticker = str(row["Ticker"]).strip().replace("/", "-")
    mic = str(row["MIC"]).strip()
    country = str(row["ISO Country"]).strip()

    if ticker in ticker_overrides:
        return ticker_overrides[ticker], "Ticker override"

    if mic in ticker_transformations:
        ticker = ticker_transformations[mic](ticker)

    if mic in mic_to_suffix:
        return ticker + mic_to_suffix[mic], "MIC rule"

    # Country-based fallback for securities with missing MIC
    country_suffix = {
        "ES": ".MC",
        "BR": ".SA",
    }

    if mic in ("0", "nan", "") and country in country_suffix:
        return ticker + country_suffix[country], "Country fallback"

    return None, "Needs review"


mapping[["YF_Ticker", "Mapping_Status"]] = mapping.apply(
    lambda row: pd.Series(map_ticker(row)),
    axis=1
)

display(mapping.head(10))
print(mapping["Mapping_Status"].value_counts())
print(f"Total listings in mapping: {len(mapping):,}")

,Ticker,MIC,ISO Country,Name,YF_Ticker,Mapping_Status
0,NVDA,XNGS,US,NVIDIA Corp,NVDA,MIC rule
1,AAPL,XNGS,US,Apple Inc,AAPL,MIC rule
2,MSFT,XNGS,US,Microsoft Corp,MSFT,MIC rule
3,AMZN,XNGS,US,Amazon.com Inc,AMZN,MIC rule
4,GOOGL,XNGS,US,Alphabet Inc,GOOGL,MIC rule
5,2330,ROCO,TW,Taiwan Semiconductor Manufactu,2330.TW,MIC rule
6,AVGO,XNGS,US,Broadcom Inc,AVGO,MIC rule
7,GOOG,XNGS,US,Alphabet Inc,GOOG,MIC rule
8,META,XNGS,US,Meta Platforms Inc,META,MIC rule
9,TSLA,XNGS,US,Tesla Inc,TSLA,MIC rule

Mapping_Status
MIC rule            9616
Ticker override      563
Country fallback     207
Needs review          34
Name: count, dtype: int64
Total listings in mapping: 10,420

In [5]:
import numpy as np
import pandas as pd
import yfinance as yf
import time

all_tickers = sorted(
    mapping.loc[mapping['YF_Ticker'].notna(), 'YF_Ticker']
    .astype(str)
    .str.strip()
    .loc[lambda s: s.ne('') & s.ne('nan')]
    .unique()
)

batches = [
    batch.tolist()
    for batch in np.array_split(all_tickers, 5)
]

for i, batch in enumerate(batches, start=1):
    print(f"Batch {i}: {len(batch):,} tickers")

def test_batch(batch_number):
    if batch_number not in range(1, 6):
        raise ValueError("batch_number must be between 1 and 5")

    batch = batches[batch_number - 1]

    print(f"Testing batch {batch_number}/5 ({len(batch):,} tickers)...")

    data = yf.download(
        tickers=batch,
        period="2d",
        interval="1d",
        auto_adjust=True,
        progress=False,
        threads=False,
        timeout=30
    )

    if data.empty:
        print("Yahoo returned no data. This may be rate-limiting.")
        return None, None

    close = data["Close"]

    # Handle a single ticker separately if necessary
    if isinstance(close, pd.Series):
        close = close.to_frame(name=batch[0])

    results = pd.DataFrame({
        "YF_Ticker": batch
    })

    results["Has_Data"] = results["YF_Ticker"].apply(
        lambda ticker: (
            ticker in close.columns
            and close[ticker].notna().any()
        )
    )

    successes = int(results["Has_Data"].sum())
    failures = len(results) - successes

    print(f"Successful: {successes:,}")
    print(f"Failed:     {failures:,}")
    print(f"Success rate: {successes / len(results) * 100:.2f}%")

    return results, results.loc[~results["Has_Data"]].copy()

Batch 1: 2,074 tickers
Batch 2: 2,074 tickers
Batch 3: 2,074 tickers
Batch 4: 2,073 tickers
Batch 5: 2,073 tickers

In [6]:
print(f"Original Excel rows: {len(df):,}")
print(f"Distinct Bloomberg listings: {len(listings):,}")
print(f"Rows in mapping: {len(mapping):,}")
print(f"Distinct Bloomberg ticker strings: {df['Ticker'].nunique():,}")
print(
    "Distinct Yahoo Finance symbols:",
    mapping.loc[
        mapping["YF_Ticker"].notna() & mapping["YF_Ticker"].ne(""),
        "YF_Ticker"
    ].nunique()
)

print("\nRepeated Bloomberg ticker strings:")
print(
    mapping[mapping["Ticker"].duplicated(keep=False)]
    .sort_values("Ticker")
    [["Ticker", "MIC", "Name", "YF_Ticker"]]
)

Original Excel rows: 10,420
Distinct Bloomberg listings: 10,420
Rows in mapping: 10,420
Distinct Bloomberg ticker strings: 9,850
Distinct Yahoo Finance symbols: 10368

Repeated Bloomberg ticker strings:
       Ticker   MIC                            Name      YF_Ticker
3544   000100  XKRX                      Yuhan Corp      000100.KS
2704   000100  XSEC       TCL Technology Group Corp      000100.SZ
5157   000155  XKRX                   Doosan Co Ltd      000155.KS
6648   000155  XSEC  Sichuan New Energy Power Co Lt      000155.SZ
9390   000157  XKRX                   Doosan Co Ltd      000157.KS
...       ...   ...                             ...            ...
4543      WPL  XNSE                   Wockhardt Ltd  WOCKPHARMA.NS
7329        Z  XNSE   Zee Entertainment Enterprises           Z.NS
2554        Z  XNGS                Zillow Group Inc              Z
3013      ZIM  XNYS  ZIM Integrated Shipping Servic            ZIM
10062     ZIM  XASX           Zimplats Holdings Ltd         ZIM.AX

[1096 rows x 4 columns]

In [7]:
# Find Yahoo Finance symbols assigned to multiple Bloomberg listings
shared_yf = mapping[
    mapping["YF_Ticker"].notna()
    & mapping["YF_Ticker"].astype(str).str.strip().ne("")
    & mapping["YF_Ticker"].duplicated(keep=False)
].sort_values(["YF_Ticker", "MIC", "Ticker"])

print(f"Rows involved in shared Yahoo symbols: {len(shared_yf)}")
print(f"Distinct shared Yahoo symbols: {shared_yf['YF_Ticker'].nunique()}")

display(
    shared_yf[
        ["Ticker", "MIC", "ISO Country", "Name", "YF_Ticker", "Mapping_Status"]
    ]
)

Rows involved in shared Yahoo symbols: 35
Distinct shared Yahoo symbols: 17

,Ticker,MIC,ISO Country,Name,YF_Ticker,Mapping_Status
2006,3105,ROCO,TW,Win Semiconductors Corp,3105.TWO,Ticker override
3686,3105,XTKS,JP,Nisshinbo Holdings Inc,3105.TWO,Ticker override
7510,STC,XKUW,KW,Kuwait Telecommunications Co,7010.SR,Ticker override
4863,STC,XNYS,US,Stewart Information Services C,7010.SR,Ticker override
793,STC,XSAU,SA,Saudi Telecom Co,7010.SR,Ticker override
9830,ARTO,XIDX,ID,Bank Jago Tbk PT,AARTIIND.NS,Ticker override
6274,ARTO,XNSE,IN,Aarti Industries Ltd,AARTIIND.NS,Ticker override
3275,APR,XNSE,IN,Apar Industries Ltd,APARINDS.NS,Ticker override
7794,APR,XWAR,PL,Auto Partner SA,APARINDS.NS,Ticker override
4926,ASTRA,XNSE,IN,Astral Ltd,ASTRAL.NS,Ticker override
5186,ASTRA,XSAU,SA,Astra Industrial Group Co,ASTRAL.NS,Ticker override
1154,BHE,XNSE,IN,Bharat Electronics Ltd,BEL.NS,Ticker override
3348,BHE,XNYS,US,Benchmark Electronics Inc,BEL.NS,Ticker override
7206,BOS,XADS,AE,Bank of Sharjah,BOSCHLTD.NS,Ticker override
3207,BOS,XNSE,IN,Bosch Ltd,BOSCHLTD.NS,Ticker override
6301,CYL,XASX,AU,Catalyst Metals Ltd,CYIENT.NS,Ticker override
6259,CYL,XNSE,IN,Cyient Ltd,CYIENT.NS,Ticker override
7289,GNP,XASX,AU,GenusPlus Group Ltd,GLENMARK.NS,Ticker override
3075,GNP,XNSE,IN,Glenmark Pharmaceuticals Ltd,GLENMARK.NS,Ticker override
3764,JSW,XNSE,IN,JSW Energy Ltd,JSWENERGY.NS,Ticker override
8488,JSW,XWAR,PL,Jastrzebska Spolka Weglowa SA,JSWENERGY.NS,Ticker override
10212,KPIG,XIDX,ID,MNC Tourism Indonesia Tbk PT,KPIGREEN.NS,Ticker override
9083,KPIG,XNSE,IN,KPI Green Energy Ltd,KPIGREEN.NS,Ticker override
2276,NDA,XETR,DE,Aurubis AG,NDA-FI.HE,Ticker override
317,NDA,XHEL,FI,Nordea Bank Abp,NDA-FI.HE,Ticker override
9524,SANL,XNSE,IN,Sanofi India Ltd,SANOFI.NS,Ticker override
9398,SANOFICO,XNSE,IN,Sanofi Consumer Healthcare Ind,SANOFI.NS,Ticker override
3469,SOTL,XNSE,IN,Sterlite Technologies Ltd,SOTL.NS,MIC rule
9827,STEC,XNSE,IN,Savita Oil Technologies Ltd,SOTL.NS,Ticker override
2644,TTAN,XNGS,US,ServiceTitan Inc,TITAN.NS,Ticker override
999,TTAN,XNSE,IN,Titan Co Ltd,TITAN.NS,Ticker override
4543,WPL,XNSE,IN,Wockhardt Ltd,WOCKPHARMA.NS,Ticker override
9568,WPL,XWAR,PL,Wirtualna Polska Holding SA,WOCKPHARMA.NS,Ticker override
1996,ST,XNYS,US,Sensata Technologies Holding P,Z74.SI,Ticker override
655,ST,XSES,SG,Singapore Telecommunications L,Z74.SI,Ticker override

In [8]:
import pandas as pd
import yfinance as yf
import time
from pathlib import Path

# Select Batch 1
batch = batches[0]

print(f"Starting Batch 1: {len(batch):,} tickers")
start_time = time.monotonic()

price_series = []
failed_tickers = []

for i, ticker in enumerate(batch, start=1):
    try:
        history = yf.Ticker(ticker).history(
            period="2y",
            interval="1d",
            auto_adjust=True,
            timeout=30
        )

        if not history.empty and history["Close"].notna().any():
            prices = history["Close"].dropna().rename(ticker)
            price_series.append(prices)
        else:
            failed_tickers.append(ticker)

    except Exception:
        failed_tickers.append(ticker)

    # Print progress every 50 tickers and at the end
    if i % 50 == 0 or i == len(batch):
        elapsed = (time.monotonic() - start_time) / 60

        print(
            f"Processed {i:,}/{len(batch):,} | "
            f"Successful: {len(price_series):,} | "
            f"Failed: {len(failed_tickers):,} | "
            f"Elapsed: {elapsed:.1f} minutes"
        )

# Combine successful price histories into one DataFrame
if price_series:
    batch1_prices = pd.concat(price_series, axis=1).sort_index()
    batch1_prices.index.name = "Date"

    # Save the data
    output_path = Path("data/price_data/batch1_prices.parquet")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    batch1_prices.to_parquet(output_path)

    print("\nDownload complete.")
    print(f"Saved to: {output_path}")
    print(f"Tickers with price data: {batch1_prices.shape[1]:,}")
    print(f"Trading dates: {batch1_prices.shape[0]:,}")
    print(f"Failed tickers: {len(failed_tickers):,}")
    print(f"Total elapsed time: {(time.monotonic() - start_time) / 60:.1f} minutes")

else:
    print("No price data was retrieved. No Parquet file was saved.")

Starting Batch 1: 2,074 tickers
Processed 50/2,074 | Successful: 50 | Failed: 0 | Elapsed: 0.4 minutes
Processed 100/2,074 | Successful: 100 | Failed: 0 | Elapsed: 0.8 minutes
Processed 150/2,074 | Successful: 150 | Failed: 0 | Elapsed: 1.1 minutes
Processed 200/2,074 | Successful: 200 | Failed: 0 | Elapsed: 1.5 minutes
Processed 250/2,074 | Successful: 250 | Failed: 0 | Elapsed: 1.9 minutes
Processed 300/2,074 | Successful: 300 | Failed: 0 | Elapsed: 2.2 minutes
Processed 350/2,074 | Successful: 350 | Failed: 0 | Elapsed: 2.6 minutes
Processed 400/2,074 | Successful: 400 | Failed: 0 | Elapsed: 2.9 minutes
Processed 450/2,074 | Successful: 450 | Failed: 0 | Elapsed: 3.3 minutes
Processed 500/2,074 | Successful: 500 | Failed: 0 | Elapsed: 3.6 minutes
Processed 550/2,074 | Successful: 550 | Failed: 0 | Elapsed: 3.9 minutes
Processed 600/2,074 | Successful: 600 | Failed: 0 | Elapsed: 4.3 minutes
Processed 650/2,074 | Successful: 650 | Failed: 0 | Elapsed: 4.6 minutes
Processed 700/2,074 | Successful: 700 | Failed: 0 | Elapsed: 5.0 minutes
Processed 750/2,074 | Successful: 750 | Failed: 0 | Elapsed: 5.3 minutes
Processed 800/2,074 | Successful: 800 | Failed: 0 | Elapsed: 5.6 minutes
Processed 850/2,074 | Successful: 850 | Failed: 0 | Elapsed: 5.9 minutes
Processed 900/2,074 | Successful: 900 | Failed: 0 | Elapsed: 6.3 minutes
Processed 950/2,074 | Successful: 950 | Failed: 0 | Elapsed: 6.6 minutes
Processed 1,000/2,074 | Successful: 1,000 | Failed: 0 | Elapsed: 7.0 minutes
Processed 1,050/2,074 | Successful: 1,050 | Failed: 0 | Elapsed: 7.4 minutes

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: 1785.TW"}}}
$1785.TW: No data found, symbol may be delisted

Processed 1,100/2,074 | Successful: 1,099 | Failed: 1 | Elapsed: 7.8 minutes

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: 1815.TW"}}}
$1815.TW: No data found, symbol may be delisted

Processed 1,150/2,074 | Successful: 1,148 | Failed: 2 | Elapsed: 8.3 minutes
Processed 1,200/2,074 | Successful: 1,198 | Failed: 2 | Elapsed: 8.7 minutes
Processed 1,250/2,074 | Successful: 1,248 | Failed: 2 | Elapsed: 9.0 minutes
Processed 1,300/2,074 | Successful: 1,298 | Failed: 2 | Elapsed: 9.4 minutes
Processed 1,350/2,074 | Successful: 1,348 | Failed: 2 | Elapsed: 9.8 minutes
Processed 1,400/2,074 | Successful: 1,398 | Failed: 2 | Elapsed: 10.2 minutes
Processed 1,450/2,074 | Successful: 1,448 | Failed: 2 | Elapsed: 10.6 minutes
Processed 1,500/2,074 | Successful: 1,498 | Failed: 2 | Elapsed: 11.0 minutes
Processed 1,550/2,074 | Successful: 1,548 | Failed: 2 | Elapsed: 11.4 minutes
Processed 1,600/2,074 | Successful: 1,598 | Failed: 2 | Elapsed: 11.7 minutes
Processed 1,650/2,074 | Successful: 1,648 | Failed: 2 | Elapsed: 12.1 minutes

$2P.SR: No data found, symbol may be delisted
$2POINTZE.AE: No data found, symbol may be delisted

Processed 1,700/2,074 | Successful: 1,696 | Failed: 4 | Elapsed: 12.6 minutes
Processed 1,750/2,074 | Successful: 1,746 | Failed: 4 | Elapsed: 12.9 minutes
Processed 1,800/2,074 | Successful: 1,796 | Failed: 4 | Elapsed: 13.2 minutes
Processed 1,850/2,074 | Successful: 1,846 | Failed: 4 | Elapsed: 13.6 minutes
Processed 1,900/2,074 | Successful: 1,896 | Failed: 4 | Elapsed: 13.9 minutes

$3078.TW: No data found, symbol may be delisted
$3088.TW: No data found, symbol may be delisted
$3131.TW: No data found, symbol may be delisted
$3163.TW: No data found, symbol may be delisted

Processed 1,950/2,074 | Successful: 1,942 | Failed: 8 | Elapsed: 14.4 minutes

$3211.TW: No data found, symbol may be delisted
$3217.TW: No data found, symbol may be delisted
$3218.TW: No data found, symbol may be delisted
$3227.TW: No data found, symbol may be delisted
$3228.TW: No data found, symbol may be delisted
$3260.TW: No data found, symbol may be delisted
$3264.TW: No data found, symbol may be delisted
$3265.TW: No data found, symbol may be delisted
$3289.TW: No data found, symbol may be delisted
$3293.TW: No data found, symbol may be delisted

Processed 2,000/2,074 | Successful: 1,982 | Failed: 18 | Elapsed: 15.1 minutes

$3324.TW: No data found, symbol may be delisted
$3357.TW: No data found, symbol may be delisted
$3362.TW: No data found, symbol may be delisted
$3363.TW: No data found, symbol may be delisted
$3374.TW: No data found, symbol may be delisted

Processed 2,050/2,074 | Successful: 2,027 | Failed: 23 | Elapsed: 15.6 minutes

$3491.TW: No data found, symbol may be delisted
$3526.TW: No data found, symbol may be delisted
$3551.TW: No data found, symbol may be delisted

Processed 2,074/2,074 | Successful: 2,048 | Failed: 26 | Elapsed: 15.9 minutes

Download complete.
Saved to: data\price_data\batch1_prices.parquet
Tickers with price data: 2,048
Trading dates: 2,041
Failed tickers: 26
Total elapsed time: 15.9 minutes

In [18]:

def download_batch(batch_number, period="2y", interval="1d"):

    # Validate batch number (1 to number of batches)
    if not 1 <= batch_number <= len(batches):
        raise ValueError(f"Choose a batch between 1 and {len(batches)}.")

    batch = batches[batch_number - 1]

    print(f"Starting Batch {batch_number}: {len(batch):,} tickers")

    start_time = time.monotonic()
    price_series = []
    failed_tickers = []

    # Download prices one ticker at a time
    for i, ticker in enumerate(batch, start=1):
        try:
            history = yf.Ticker(ticker).history(
                period=period,
                interval=interval,
                auto_adjust=True,
                timeout=30
            )

            if not history.empty and history["Close"].notna().any():
                prices = history["Close"].dropna().rename(ticker)

                # Normalise timestamps before combining exchanges
                prices.index = prices.index.normalize()

                if prices.index.has_duplicates:
                    failed_tickers.append(ticker)
                else:
                    price_series.append(prices)
            else:
                failed_tickers.append(ticker)

        except Exception:
            failed_tickers.append(ticker)

        # Print progress every 50 tickers and at the end
        if i % 50 == 0 or i == len(batch):
            elapsed = (time.monotonic() - start_time) / 60

            print(
                f"Processed {i:,}/{len(batch):,} | "
                f"Successful: {len(price_series):,} | "
                f"Failed: {len(failed_tickers):,} | "
                f"Elapsed: {elapsed:.1f} minutes"
            )

    # Check whether any data was retrieved
    if not price_series:
        print("No price data was retrieved. No price file was saved.")
        return None

    # Combine all successfully retrieved price histories
    prices_df = pd.concat(price_series, axis=1).sort_index()
    prices_df.index.name = "Date"

    # Create output folder
    output_dir = Path("data/price_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save price data
    prices_path = output_dir / f"batch{batch_number}_prices.parquet"
    prices_df.to_parquet(prices_path)

    # Save the failed ticker list
    failed_path = output_dir / f"batch{batch_number}_failed_tickers.csv"
    pd.DataFrame({"Ticker": failed_tickers}).to_csv(
        failed_path, index=False
    )

    # Print final summary
    elapsed = (time.monotonic() - start_time) / 60

    print(f"\nBatch {batch_number} complete.")
    print(f"Price data saved: {prices_path}")
    print(f"Failed ticker list saved: {failed_path}")
    print(f"Tickers with price data: {prices_df.shape[1]:,}")
    print(f"Failed tickers: {len(failed_tickers):,}")
    print(f"Trading dates: {prices_df.shape[0]:,}")
    print(f"Total elapsed time: {elapsed:.1f} minutes")

    return prices_df, failed_tickers

In [19]:
batch2_prices, batch2_failed = download_batch(2)

Starting Batch 2: 2,074 tickers

$3587.TW: No data found, symbol may be delisted
$3675.TW: No data found, symbol may be delisted
$3680.TW: No data found, symbol may be delisted
$3691.TW: No data found, symbol may be delisted
$3693.TW: No data found, symbol may be delisted
$3707.TW: No data found, symbol may be delisted
$3718.TW: No data found, symbol may be delisted

Processed 50/2,074 | Successful: 43 | Failed: 7 | Elapsed: 0.6 minutes
Processed 100/2,074 | Successful: 93 | Failed: 7 | Elapsed: 0.9 minutes

$4105.TW: No data found, symbol may be delisted
$4114.TW: No data found, symbol may be delisted
$4123.TW: No data found, symbol may be delisted
$4147.TW: No data found, symbol may be delisted
$4162.TW: No data found, symbol may be delisted

Processed 150/2,074 | Successful: 138 | Failed: 12 | Elapsed: 1.5 minutes

$4506.TW: No data found, symbol may be delisted

Processed 200/2,074 | Successful: 187 | Failed: 13 | Elapsed: 1.9 minutes

$4728.TW: No data found, symbol may be delisted
$4743.TW: No data found, symbol may be delisted
$4749.TW: No data found, symbol may be delisted

Processed 250/2,074 | Successful: 234 | Failed: 16 | Elapsed: 2.3 minutes

$4768.TW: No data found, symbol may be delisted
$4772.TW: No data found, symbol may be delisted
$4966.TW: No data found, symbol may be delisted
$4971.TW: No data found, symbol may be delisted
$4979.TW: No data found, symbol may be delisted
$4991.TW: No data found, symbol may be delisted

Processed 300/2,074 | Successful: 278 | Failed: 22 | Elapsed: 2.9 minutes

$5009.TW: No data found, symbol may be delisted
$5213.TW: No data found, symbol may be delisted
$5289.TW: No data found, symbol may be delisted
$5309.TW: No data found, symbol may be delisted
$5314.TW: No data found, symbol may be delisted
$5340.TW: No data found, symbol may be delisted
$5351.TW: No data found, symbol may be delisted

Processed 350/2,074 | Successful: 321 | Failed: 29 | Elapsed: 3.5 minutes

$5425.TW: No data found, symbol may be delisted
$5439.TW: No data found, symbol may be delisted
$5443.TW: No data found, symbol may be delisted
$5475.TW: No data found, symbol may be delisted
$5478.TW: No data found, symbol may be delisted
$5483.TW: No data found, symbol may be delisted
$5508.TW: No data found, symbol may be delisted
$5530.TW: No data found, symbol may be delisted
$5536.TW: No data found, symbol may be delisted
$5609.TW: No data found, symbol may be delisted
$5864.TW: No data found, symbol may be delisted

Processed 400/2,074 | Successful: 360 | Failed: 40 | Elapsed: 4.1 minutes

$5903.TW: No data found, symbol may be delisted
$5904.TW: No data found, symbol may be delisted

Processed 450/2,074 | Successful: 408 | Failed: 42 | Elapsed: 4.5 minutes
Processed 500/2,074 | Successful: 458 | Failed: 42 | Elapsed: 4.9 minutes
Processed 550/2,074 | Successful: 508 | Failed: 42 | Elapsed: 5.3 minutes
Processed 600/2,074 | Successful: 558 | Failed: 42 | Elapsed: 5.6 minutes
Processed 650/2,074 | Successful: 608 | Failed: 42 | Elapsed: 6.0 minutes
Processed 700/2,074 | Successful: 658 | Failed: 42 | Elapsed: 6.3 minutes

$6016.TW: No data found, symbol may be delisted

Processed 750/2,074 | Successful: 707 | Failed: 43 | Elapsed: 6.7 minutes
Processed 800/2,074 | Successful: 757 | Failed: 43 | Elapsed: 7.0 minutes

$6023.TW: No data found, symbol may be delisted

Processed 850/2,074 | Successful: 806 | Failed: 44 | Elapsed: 7.4 minutes
Processed 900/2,074 | Successful: 856 | Failed: 44 | Elapsed: 7.8 minutes
Processed 950/2,074 | Successful: 906 | Failed: 44 | Elapsed: 8.1 minutes

$6121.TW: No data found, symbol may be delisted
$6125.TW: No data found, symbol may be delisted
$6138.TW: No data found, symbol may be delisted
$6146.TW: No data found, symbol may be delisted
$6147.TW: No data found, symbol may be delisted
$6173.TW: No data found, symbol may be delisted
$6182.TW: No data found, symbol may be delisted
$6187.TW: No data found, symbol may be delisted
$6188.TW: No data found, symbol may be delisted
$6217.TW: No data found, symbol may be delisted

Processed 1,000/2,074 | Successful: 946 | Failed: 54 | Elapsed: 8.8 minutes

$6231.TW: No data found, symbol may be delisted
$6245.TW: No data found, symbol may be delisted
$6261.TW: No data found, symbol may be delisted
$6279.TW: No data found, symbol may be delisted
$6284.TW: No data found, symbol may be delisted
$6290.TW: No data found, symbol may be delisted
$6291.TW: No data found, symbol may be delisted

Processed 1,050/2,074 | Successful: 989 | Failed: 61 | Elapsed: 9.4 minutes

$6469.TW: No data found, symbol may be delisted
$6510.TW: No data found, symbol may be delisted

Processed 1,100/2,074 | Successful: 1,037 | Failed: 63 | Elapsed: 9.8 minutes

$6535.TW: No data found, symbol may be delisted
$6547.TW: No data found, symbol may be delisted
$6548.TW: No data found, symbol may be delisted
$6561.TW: No data found, symbol may be delisted
$6576.TW: No data found, symbol may be delisted
$6584.TW: No data found, symbol may be delisted
$6613.TW: No data found, symbol may be delisted
$6617.TW: No data found, symbol may be delisted
$6620.TW: No data found, symbol may be delisted
$6640.TW: No data found, symbol may be delisted
$6643.TW: No data found, symbol may be delisted
$6664.TW: No data found, symbol may be delisted
$6667.TW: No data found, symbol may be delisted
$6679.TW: No data found, symbol may be delisted
$6683.TW: No data found, symbol may be delisted

Processed 1,150/2,074 | Successful: 1,072 | Failed: 78 | Elapsed: 10.6 minutes

$6712.TW: No data found, symbol may be delisted
$6739.TW: No data found, symbol may be delisted
$6788.TW: No data found, symbol may be delisted
$6803.TW: No data found, symbol may be delisted

Processed 1,200/2,074 | Successful: 1,118 | Failed: 82 | Elapsed: 11.1 minutes
Processed 1,250/2,074 | Successful: 1,168 | Failed: 82 | Elapsed: 11.5 minutes
Processed 1,300/2,074 | Successful: 1,218 | Failed: 82 | Elapsed: 11.8 minutes
Processed 1,350/2,074 | Successful: 1,268 | Failed: 82 | Elapsed: 12.2 minutes

$6903.TW: No data found, symbol may be delisted

Processed 1,400/2,074 | Successful: 1,317 | Failed: 83 | Elapsed: 12.6 minutes
Processed 1,450/2,074 | Successful: 1,367 | Failed: 83 | Elapsed: 13.0 minutes
Processed 1,500/2,074 | Successful: 1,417 | Failed: 83 | Elapsed: 13.4 minutes

$7734.TW: No data found, symbol may be delisted
$7751.TW: No data found, symbol may be delisted
$7805.TW: No data found, symbol may be delisted
$7828.TW: No data found, symbol may be delisted

Processed 1,550/2,074 | Successful: 1,463 | Failed: 87 | Elapsed: 13.9 minutes

$8027.TW: No data found, symbol may be delisted
$8042.TW: No data found, symbol may be delisted
$8050.TW: No data found, symbol may be delisted
$8064.TW: No data found, symbol may be delisted
$8069.TW: No data found, symbol may be delisted

Processed 1,600/2,074 | Successful: 1,508 | Failed: 92 | Elapsed: 14.4 minutes

$8086.TW: No data found, symbol may be delisted
$8096.TW: No data found, symbol may be delisted
$8155.TW: No data found, symbol may be delisted
$8255.TW: No data found, symbol may be delisted

Processed 1,650/2,074 | Successful: 1,554 | Failed: 96 | Elapsed: 14.9 minutes

$8358.TW: No data found, symbol may be delisted
$8415.TW: No data found, symbol may be delisted
$8436.TW: No data found, symbol may be delisted

Processed 1,700/2,074 | Successful: 1,601 | Failed: 99 | Elapsed: 15.4 minutes

$8908.TW: No data found, symbol may be delisted
$8932.TW: No data found, symbol may be delisted
$8936.TW: No data found, symbol may be delisted
$8937.TW: No data found, symbol may be delisted

Processed 1,750/2,074 | Successful: 1,647 | Failed: 103 | Elapsed: 15.9 minutes
Processed 1,800/2,074 | Successful: 1,697 | Failed: 103 | Elapsed: 16.3 minutes
Processed 1,850/2,074 | Successful: 1,747 | Failed: 103 | Elapsed: 16.7 minutes
Processed 1,900/2,074 | Successful: 1,797 | Failed: 103 | Elapsed: 17.0 minutes
Processed 1,950/2,074 | Successful: 1,847 | Failed: 103 | Elapsed: 17.4 minutes

$99SMART.KL: No data found, symbol may be delisted
$AAGB.KL: No data found, symbol may be delisted
$AAREIT.SI: No data found, symbol may be delisted
$ABANK.KL: No data found, symbol may be delisted

Processed 2,000/2,074 | Successful: 1,893 | Failed: 107 | Elapsed: 17.9 minutes

$ABMB.KL: No data found, symbol may be delisted
$AC.PS: No data found, symbol may be delisted
$ACEN.PS: No data found, symbol may be delisted

Processed 2,050/2,074 | Successful: 1,940 | Failed: 110 | Elapsed: 18.4 minutes

$ACSM.KL: No data found, symbol may be delisted
$ADCB.AE: No data found, symbol may be delisted

Processed 2,074/2,074 | Successful: 1,962 | Failed: 112 | Elapsed: 18.6 minutes

Batch 2 complete.
Price data saved: data\price_data\batch2_prices.parquet
Failed ticker list saved: data\price_data\batch2_failed_tickers.csv
Tickers with price data: 1,962
Failed tickers: 112
Trading dates: 5,893
Total elapsed time: 18.7 minutes

In [20]:
batch3_prices, batch3_failed = download_batch(3)

Starting Batch 3: 2,074 tickers

$ADES.SR: No data found, symbol may be delisted
$ADIB.AE: No data found, symbol may be delisted
$ADNH.AE: No data found, symbol may be delisted
$ADNHC.AE: No data found, symbol may be delisted
$ADNOCDIS.AE: No data found, symbol may be delisted
$ADNOCDRI.AE: No data found, symbol may be delisted
$ADNOCLS.AE: No data found, symbol may be delisted
$ADPORTS.AE: No data found, symbol may be delisted
$ADSB.AE: No data found, symbol may be delisted
$AEM.SI: No data found, symbol may be delisted
$AEON.KL: No data found, symbol may be delisted

Processed 50/2,074 | Successful: 39 | Failed: 11 | Elapsed: 0.7 minutes

$AGI.PS: No data found, symbol may be delisted
$AGILITY.AE: No data found, symbol may be delisted
$AGTHIA.AE: No data found, symbol may be delisted
$AGUILCPO.MX: No data found, symbol may be delisted

Processed 100/2,074 | Successful: 85 | Failed: 15 | Elapsed: 1.2 minutes

$AIRARABI.AE: No data found, symbol may be delisted
$AJMANBAN.AE: No data found, symbol may be delisted
$ALANDALU.SR: No data found, symbol may be delisted
$ALARABIA.SR: No data found, symbol may be delisted
$ALARKAN.SR: No data found, symbol may be delisted

Processed 150/2,074 | Successful: 130 | Failed: 20 | Elapsed: 1.7 minutes

$ALASEEL.SR: No data found, symbol may be delisted
$ALBABTAI.SR: No data found, symbol may be delisted
$ALBI.SR: No data found, symbol may be delisted
$ALCO.SR: No data found, symbol may be delisted
$ALDAR.AE: No data found, symbol may be delisted
$ALDAWAA.SR: No data found, symbol may be delisted
$ALDREES.SR: No data found, symbol may be delisted
$ALEFEDT.AE: No data found, symbol may be delisted
$ALHAMMAD.SR: No data found, symbol may be delisted
$ALI.PS: No data found, symbol may be delisted
$ALLZ.KL: No data found, symbol may be delisted
$ALMAJDIA.SR: No data found, symbol may be delisted
$ALMAJED.SR: No data found, symbol may be delisted

Processed 200/2,074 | Successful: 167 | Failed: 33 | Elapsed: 2.4 minutes

$ALMAWARI.SR: No data found, symbol may be delisted
$ALMOOSA.SR: No data found, symbol may be delisted
$ALMUNAJE.SR: No data found, symbol may be delisted
$ALPHA.KL: No data found, symbol may be delisted
$ALPHADAT.AE: No data found, symbol may be delisted
$ALPHADHA.AE: No data found, symbol may be delisted
$ALSAIF.SR: No data found, symbol may be delisted
$ALTIJARI.KW: No data found, symbol may be delisted
$AMAK.SR: No data found, symbol may be delisted

Processed 250/2,074 | Successful: 208 | Failed: 42 | Elapsed: 3.1 minutes

$AMM.KL: No data found, symbol may be delisted
$AMR.AE: No data found, symbol may be delisted
$ANAN.AE: No data found, symbol may be delisted

Processed 300/2,074 | Successful: 255 | Failed: 45 | Elapsed: 3.5 minutes

$ANDINAB.SN: No data found, symbol may be delisted
$AOTHAIM.SR: No data found, symbol may be delisted
$AP-U.TO: No data found, symbol may be delisted
$AP.PS: No data found, symbol may be delisted
$APCO.SR: No data found, symbol may be delisted
$APEX.AE: No data found, symbol may be delisted

Processed 350/2,074 | Successful: 299 | Failed: 51 | Elapsed: 4.1 minutes

$APPC.SR: No data found, symbol may be delisted
$APX.PS: No data found, symbol may be delisted
$ARABIAND.SR: No data found, symbol may be delisted
$ARABIANM.SR: No data found, symbol may be delisted
$ARCCI.SR: No data found, symbol may be delisted
$ARCCO.SR: No data found, symbol may be delisted
$ARDCO.SR: No data found, symbol may be delisted
$ARNB.SR: No data found, symbol may be delisted

Processed 400/2,074 | Successful: 341 | Failed: 59 | Elapsed: 4.7 minutes

$ASM.AE: No data found, symbol may be delisted
$ASM.BO: No data found, symbol may be delisted

Processed 450/2,074 | Successful: 389 | Failed: 61 | Elapsed: 5.1 minutes

$AT.PS: No data found, symbol may be delisted
$ATAA.SR: No data found, symbol may be delisted

Processed 500/2,074 | Successful: 437 | Failed: 63 | Elapsed: 5.5 minutes

$AVALONPH.SR: No data found, symbol may be delisted
$AVNT.NS: No data found, symbol may be delisted
$AWPT.SR: No data found, symbol may be delisted
$AXIATA.KL: No data found, symbol may be delisted

Processed 550/2,074 | Successful: 483 | Failed: 67 | Elapsed: 6.0 minutes

$AXRB.KL: No data found, symbol may be delisted
$AZM.SR: No data found, symbol may be delisted
$BAB.KL: No data found, symbol may be delisted
$BAL.SI: No data found, symbol may be delisted

Processed 600/2,074 | Successful: 529 | Failed: 71 | Elapsed: 6.5 minutes

$BAWAN.SR: No data found, symbol may be delisted

Processed 650/2,074 | Successful: 578 | Failed: 72 | Elapsed: 6.9 minutes

$BC.KL: No data found, symbol may be delisted
$BDO.PS: No data found, symbol may be delisted
$BEI-U.TO: No data found, symbol may be delisted

Processed 700/2,074 | Successful: 625 | Failed: 75 | Elapsed: 7.4 minutes
Processed 750/2,074 | Successful: 675 | Failed: 75 | Elapsed: 7.7 minutes

$BIMB.KL: No data found, symbol may be delisted
$BINDAWOO.SR: No data found, symbol may be delisted
$BJAZ.SR: No data found, symbol may be delisted
$BLA.NS: No data found, symbol may be delisted

Processed 800/2,074 | Successful: 721 | Failed: 79 | Elapsed: 8.2 minutes

$BLOOM.PS: No data found, symbol may be delisted
$BNASTRA.KL: No data found, symbol may be delisted

Processed 850/2,074 | Successful: 769 | Failed: 81 | Elapsed: 8.7 minutes

$BOOT.BO: No data found, symbol may be delisted
$BPI.PS: No data found, symbol may be delisted
$BRC.SI: No data found, symbol may be delisted

Processed 900/2,074 | Successful: 816 | Failed: 84 | Elapsed: 9.1 minutes

$BSAN.SN: No data found, symbol may be delisted
$BUDGET.SR: No data found, symbol may be delisted
$BUPA.SR: No data found, symbol may be delisted

Processed 950/2,074 | Successful: 863 | Failed: 87 | Elapsed: 9.5 minutes

$BURJEEL.AE: No data found, symbol may be delisted
$BURSA.KL: No data found, symbol may be delisted
$CAB.KL: No data found, symbol may be delisted

Processed 1,000/2,074 | Successful: 910 | Failed: 90 | Elapsed: 10.0 minutes

$CAO.SI: No data found, symbol may be delisted
$CAPITALA.KL: No data found, symbol may be delisted
$CAR-U.TO: No data found, symbol may be delisted
$CARE.NS: No data found, symbol may be delisted
$CARE.SR: No data found, symbol may be delisted
$CAREIT.SI: No data found, symbol may be delisted
$CATERING.SR: No data found, symbol may be delisted
$CBK.NS: No data found, symbol may be delisted

Processed 1,050/2,074 | Successful: 952 | Failed: 98 | Elapsed: 10.6 minutes

$CD.SI: No data found, symbol may be delisted
$CDB.KL: No data found, symbol may be delisted
$CDREIT.SI: No data found, symbol may be delisted

Processed 1,100/2,074 | Successful: 999 | Failed: 101 | Elapsed: 11.0 minutes

$CENCOMAL.SN: No data found, symbol may be delisted
$CENOMI.SR: No data found, symbol may be delisted
$CENOMICE.SR: No data found, symbol may be delisted
$CENT.SI: No data found, symbol may be delisted
$CF.NS: No data found, symbol may be delisted
$CHE-U.TO: No data found, symbol may be delisted

Processed 1,150/2,074 | Successful: 1,043 | Failed: 107 | Elapsed: 11.6 minutes

$CHEMICAL.SR: No data found, symbol may be delisted
$CHGP.KL: No data found, symbol may be delisted
$CHP-U.TO: No data found, symbol may be delisted
$CICT.SI: No data found, symbol may be delisted
$CIMB.KL: No data found, symbol may be delisted
$CIT.SI: No data found, symbol may be delisted
$CITYC.SR: No data found, symbol may be delisted
$CLAR.SI: No data found, symbol may be delisted

Processed 1,200/2,074 | Successful: 1,085 | Failed: 115 | Elapsed: 12.1 minutes

$CLAS.SI: No data found, symbol may be delisted
$CLCT.SI: No data found, symbol may be delisted
$CLI.SI: No data found, symbol may be delisted
$CLINT.SI: No data found, symbol may be delisted
$CLMT.KL: No data found, symbol may be delisted

Processed 1,250/2,074 | Successful: 1,130 | Failed: 120 | Elapsed: 12.6 minutes

$CNPF.PS: No data found, symbol may be delisted
$CNVRG.PS: No data found, symbol may be delisted

Processed 1,300/2,074 | Successful: 1,178 | Failed: 122 | Elapsed: 13.1 minutes

$CONCHA.SN: No data found, symbol may be delisted

Processed 1,350/2,074 | Successful: 1,227 | Failed: 123 | Elapsed: 13.5 minutes

$CRR-U.TO: No data found, symbol may be delisted
$CRS.NS: No data found, symbol may be delisted
$CRT-U.TO: No data found, symbol may be delisted

Processed 1,400/2,074 | Successful: 1,274 | Failed: 126 | Elapsed: 13.9 minutes

$CSH-U.TO: No data found, symbol may be delisted
$CTOS.KL: No data found, symbol may be delisted
$CU.NS: No data found, symbol may be delisted

Processed 1,450/2,074 | Successful: 1,321 | Failed: 129 | Elapsed: 14.4 minutes

$DALLAH.SR: No data found, symbol may be delisted
$DANA.AE: No data found, symbol may be delisted

Processed 1,500/2,074 | Successful: 1,369 | Failed: 131 | Elapsed: 14.8 minutes

$DBB.KL: No data found, symbol may be delisted
$DEHB.KL: No data found, symbol may be delisted
$DERAYAH.SR: No data found, symbol may be delisted

Processed 1,550/2,074 | Successful: 1,416 | Failed: 134 | Elapsed: 15.2 minutes

$DFI.SI: No data found, symbol may be delisted
$DIR-U.TO: No data found, symbol may be delisted
$DLG.KL: No data found, symbol may be delisted
$DLM.KL: No data found, symbol may be delisted

Processed 1,600/2,074 | Successful: 1,462 | Failed: 138 | Elapsed: 15.7 minutes

$DMC.PS: No data found, symbol may be delisted
$DNL.PS: No data found, symbol may be delisted

Processed 1,650/2,074 | Successful: 1,510 | Failed: 140 | Elapsed: 16.2 minutes

$DRB.KL: No data found, symbol may be delisted

Processed 1,700/2,074 | Successful: 1,559 | Failed: 141 | Elapsed: 16.6 minutes

$DXN.KL: No data found, symbol may be delisted
$E7.AE: No data found, symbol may be delisted
$EACCO.SR: No data found, symbol may be delisted
$EAND.AE: No data found, symbol may be delisted
$EAST.KL: No data found, symbol may be delisted
$EASTPIPE.SR: No data found, symbol may be delisted
$EAT.SR: No data found, symbol may be delisted
$ECOPETL.CL: No data found, symbol may be delisted
$ECOSHOP.KL: No data found, symbol may be delisted
$ECW.KL: No data found, symbol may be delisted
$EDARAT.SR: No data found, symbol may be delisted

Processed 1,750/2,074 | Successful: 1,598 | Failed: 152 | Elapsed: 17.3 minutes

$EG.KL: No data found, symbol may be delisted
$EIC.SR: No data found, symbol may be delisted

Processed 1,800/2,074 | Successful: 1,646 | Failed: 154 | Elapsed: 17.7 minutes

$ELM.SR: No data found, symbol may be delisted
$ELRIDGE.KL: No data found, symbol may be delisted
$EMAAR.SR: No data found, symbol may be delisted
$EMI.PS: No data found, symbol may be delisted
$EMOBILIT.AE: No data found, symbol may be delisted

Processed 1,850/2,074 | Successful: 1,691 | Failed: 159 | Elapsed: 18.2 minutes

$EMSTEEL.AE: No data found, symbol may be delisted
$ENELCHIL.SN: No data found, symbol may be delisted

Processed 1,900/2,074 | Successful: 1,739 | Failed: 161 | Elapsed: 18.6 minutes

$EREIT.SI: No data found, symbol may be delisted
$ESAB.NS: No data found, symbol may be delisted

Processed 1,950/2,074 | Successful: 1,787 | Failed: 163 | Elapsed: 19.1 minutes

$ETIHADEN.AE: No data found, symbol may be delisted

Processed 2,000/2,074 | Successful: 1,836 | Failed: 164 | Elapsed: 19.4 minutes

$EXTRA.SR: No data found, symbol may be delisted
$FAKEEHCA.SR: No data found, symbol may be delisted
$FCR-U.TO: No data found, symbol may be delisted
$FCT.SI: No data found, symbol may be delisted
$FEH.SI: No data found, symbol may be delisted

Processed 2,050/2,074 | Successful: 1,881 | Failed: 169 | Elapsed: 19.9 minutes

$FEHT.SI: No data found, symbol may be delisted
$FERTIGLB.AE: No data found, symbol may be delisted
$FFB.KL: No data found, symbol may be delisted
$FGEN.PS: No data found, symbol may be delisted

Processed 2,074/2,074 | Successful: 1,901 | Failed: 173 | Elapsed: 20.2 minutes

Batch 3 complete.
Price data saved: data\price_data\batch3_prices.parquet
Failed ticker list saved: data\price_data\batch3_failed_tickers.csv
Tickers with price data: 1,901
Failed tickers: 173
Trading dates: 5,884
Total elapsed time: 20.2 minutes

In [21]:
batch4_prices, batch4_failed = download_batch(4)

Starting Batch 4: 2,073 tickers

$FIBRAMQ.MX: No data found, symbol may be delisted
$FIBRAPL.MX: No data found, symbol may be delisted
$FIRSTMIL.SR: No data found, symbol may be delisted
$FLT.SI: No data found, symbol may be delisted
$FLYNAS.SR: No data found, symbol may be delisted

Processed 50/2,073 | Successful: 45 | Failed: 5 | Elapsed: 0.5 minutes

$FNH.KL: No data found, symbol may be delisted
$FOURTHMI.SR: No data found, symbol may be delisted
$FR.SI: No data found, symbol may be delisted
$FRCB.KL: No data found, symbol may be delisted

Processed 100/2,073 | Successful: 91 | Failed: 9 | Elapsed: 1.1 minutes

$GAM.KL: No data found, symbol may be delisted

Processed 150/2,073 | Successful: 140 | Failed: 10 | Elapsed: 1.4 minutes

$GAS.SR: No data found, symbol may be delisted
$GENM.KL: No data found, symbol may be delisted
$GENP.KL: No data found, symbol may be delisted
$GENS.SI: No data found, symbol may be delisted
$GENT.KL: No data found, symbol may be delisted

Processed 200/2,073 | Successful: 185 | Failed: 15 | Elapsed: 2.0 minutes

$GGR.SI: No data found, symbol may be delisted
$GHITHA.AE: No data found, symbol may be delisted
$GIG.SR: No data found, symbol may be delisted
$GLB.IR: possibly delisted; no price data found  (period=2y)
$GLO.PS: No data found, symbol may be delisted

Processed 250/2,073 | Successful: 230 | Failed: 20 | Elapsed: 2.5 minutes

$GLV.IR: No data found, symbol may be delisted
$GMB.KL: No data found, symbol may be delisted

Processed 300/2,073 | Successful: 278 | Failed: 22 | Elapsed: 2.9 minutes

$GREATEC.KL: No data found, symbol may be delisted
$GROUPFIV.SR: No data found, symbol may be delisted
$GRT-U.TO: No data found, symbol may be delisted

Processed 350/2,073 | Successful: 325 | Failed: 25 | Elapsed: 3.4 minutes

$GRUPOARG.CL: No data found, symbol may be delisted
$GRUPOSUR.CL: No data found, symbol may be delisted
$GTCAP.PS: No data found, symbol may be delisted
$GUAN.KL: No data found, symbol may be delisted
$HAL.KL: No data found, symbol may be delisted

Processed 400/2,073 | Successful: 370 | Failed: 30 | Elapsed: 3.9 minutes

$HAPL.KL: No data found, symbol may be delisted
$HART.KL: No data found, symbol may be delisted
$HB.SR: No data found, symbol may be delisted

Processed 450/2,073 | Successful: 417 | Failed: 33 | Elapsed: 4.4 minutes

$HEIM.KL: No data found, symbol may be delisted
$HEIM.NS: No data found, symbol may be delisted
$HG.SI: No data found, symbol may be delisted
$HIBI.KL: No data found, symbol may be delisted
$HKL.SI: No data found, symbol may be delisted
$HLA.SI: No data found, symbol may be delisted
$HLBK.KL: No data found, symbol may be delisted
$HLFG.KL: No data found, symbol may be delisted

Processed 500/2,073 | Successful: 459 | Failed: 41 | Elapsed: 5.0 minutes

$HLI.KL: No data found, symbol may be delisted
$HMN.NS: No data found, symbol may be delisted
$HPAR.SI: No data found, symbol may be delisted
$HR-U.TO: No data found, symbol may be delisted

Processed 550/2,073 | Successful: 505 | Failed: 45 | Elapsed: 5.5 minutes

$HTFL.NS: No data found, symbol may be delisted
$HUMANSFT.KW: No data found, symbol may be delisted
$HUME.KL: No data found, symbol may be delisted

Processed 600/2,073 | Successful: 552 | Failed: 48 | Elapsed: 5.9 minutes

$ICT.PS: No data found, symbol may be delisted

Processed 650/2,073 | Successful: 601 | Failed: 49 | Elapsed: 6.3 minutes

$IFAST.SI: No data found, symbol may be delisted
$IGBCR.KL: No data found, symbol may be delisted
$IGBREIT.KL: No data found, symbol may be delisted
$IHH.KL: No data found, symbol may be delisted
$IJM.KL: No data found, symbol may be delisted

Processed 700/2,073 | Successful: 646 | Failed: 54 | Elapsed: 6.8 minutes

$INGR.NS: No data found, symbol may be delisted
$INRI.KL: No data found, symbol may be delisted

Processed 750/2,073 | Successful: 694 | Failed: 56 | Elapsed: 7.3 minutes

$INTEGRAT.KW: No data found, symbol may be delisted
$INVICTUS.AE: No data found, symbol may be delisted
$IOI.KL: No data found, symbol may be delisted
$IOIPG.KL: No data found, symbol may be delisted

Processed 800/2,073 | Successful: 740 | Failed: 60 | Elapsed: 7.8 minutes

$ITMAX.KL: No data found, symbol may be delisted

Processed 850/2,073 | Successful: 789 | Failed: 61 | Elapsed: 8.2 minutes

$JADCO.SR: No data found, symbol may be delisted
$JAHEZ.SR: No data found, symbol may be delisted
$JAMJOOMP.SR: No data found, symbol may be delisted
$JARIR.SR: No data found, symbol may be delisted
$JCNC.SI: No data found, symbol may be delisted
$JFC.PS: No data found, symbol may be delisted
$JGS.PS: No data found, symbol may be delisted

Processed 900/2,073 | Successful: 832 | Failed: 68 | Elapsed: 8.8 minutes

$JM.NS: No data found, symbol may be delisted
$JM.SI: No data found, symbol may be delisted
$JOMAR.SR: No data found, symbol may be delisted
$JPG.KL: No data found, symbol may be delisted

Processed 950/2,073 | Successful: 878 | Failed: 72 | Elapsed: 9.3 minutes

$KAYAN.SR: No data found, symbol may be delisted
$KDCREIT.SI: No data found, symbol may be delisted
$KEC.SR: No data found, symbol may be delisted
$KEEPR.PS: No data found, symbol may be delisted
$KEP.SI: No data found, symbol may be delisted

Processed 1,000/2,073 | Successful: 923 | Failed: 77 | Elapsed: 9.8 minutes

$KEYFIELD.KL: No data found, symbol may be delisted
$KGRB.KL: No data found, symbol may be delisted
$KIT.SI: No data found, symbol may be delisted
$KLK.KL: No data found, symbol may be delisted

Processed 1,050/2,073 | Successful: 969 | Failed: 81 | Elapsed: 10.3 minutes

$KMB.NS: No data found, symbol may be delisted
$KMP-U.TO: No data found, symbol may be delisted
$KOPI.KL: No data found, symbol may be delisted
$KPG.KL: No data found, symbol may be delisted
$KPJ.KL: No data found, symbol may be delisted
$KREIT.SI: No data found, symbol may be delisted
$KRI.KL: No data found, symbol may be delisted

Processed 1,100/2,073 | Successful: 1,012 | Failed: 88 | Elapsed: 10.9 minutes

$KSL.KL: No data found, symbol may be delisted
$KYGA.IR: No data found, symbol may be delisted
$LACOMUBC.MX: No data found, symbol may be delisted
$LADUN.SR: No data found, symbol may be delisted

Processed 1,150/2,073 | Successful: 1,058 | Failed: 92 | Elapsed: 11.4 minutes

$LEEJAM.SR: No data found, symbol may be delisted
$LFG.KL: No data found, symbol may be delisted
$LHIB.KL: No data found, symbol may be delisted

Processed 1,200/2,073 | Successful: 1,105 | Failed: 95 | Elapsed: 11.8 minutes

$LIVEPOLC.MX: No data found, symbol may be delisted
$LMC.KL: No data found, symbol may be delisted

Processed 1,250/2,073 | Successful: 1,153 | Failed: 97 | Elapsed: 12.2 minutes

$LREIT.SI: No data found, symbol may be delisted
$LSH.KL: No data found, symbol may be delisted
$LUBEREF.SR: No data found, symbol may be delisted
$LULU.AE: No data found, symbol may be delisted

Processed 1,300/2,073 | Successful: 1,199 | Failed: 101 | Elapsed: 12.7 minutes

$LUMI.SR: No data found, symbol may be delisted
$MAG.KL: No data found, symbol may be delisted
$MAHARAH.SR: No data found, symbol may be delisted

Processed 1,350/2,073 | Successful: 1,246 | Failed: 104 | Elapsed: 13.2 minutes

$MALLPLAZ.SN: No data found, symbol may be delisted
$MARAFIQ.SR: No data found, symbol may be delisted
$MASAR.SR: No data found, symbol may be delisted
$MAXIS.KL: No data found, symbol may be delisted

Processed 1,400/2,073 | Successful: 1,292 | Failed: 108 | Elapsed: 13.7 minutes

$MBM.KL: No data found, symbol may be delisted
$MBSB.KL: No data found, symbol may be delisted
$MBT.PS: No data found, symbol may be delisted
$MCDCO.SR: No data found, symbol may be delisted
$MCH.KL: No data found, symbol may be delisted
$MDA.NS: No data found, symbol may be delisted
$MEDGULF.SR: No data found, symbol may be delisted
$MEG.PS: No data found, symbol may be delisted

Processed 1,450/2,073 | Successful: 1,334 | Failed: 116 | Elapsed: 14.3 minutes

$MEH.SR: No data found, symbol may be delisted
$MEPC.SR: No data found, symbol may be delisted
$MER.PS: No data found, symbol may be delisted
$MFCB.KL: No data found, symbol may be delisted

Processed 1,500/2,073 | Successful: 1,380 | Failed: 120 | Elapsed: 14.7 minutes

$MI.KL: No data found, symbol may be delisted
$MIAHONA.SR: No data found, symbol may be delisted
$MINT.SI: No data found, symbol may be delisted
$MIS.SR: No data found, symbol may be delisted
$MISC.KL: No data found, symbol may be delisted
$MLK.KL: No data found, symbol may be delisted
$MLT.SI: No data found, symbol may be delisted

Processed 1,550/2,073 | Successful: 1,423 | Failed: 127 | Elapsed: 15.3 minutes

$MNHLDG.KL: No data found, symbol may be delisted
$MNRB.KL: No data found, symbol may be delisted
$MODERNMI.SR: No data found, symbol may be delisted
$MONDE.PS: No data found, symbol may be delisted
$MOUWASAT.SR: No data found, symbol may be delisted
$MPACT.SI: No data found, symbol may be delisted
$MPI.KL: No data found, symbol may be delisted

Processed 1,600/2,073 | Successful: 1,466 | Failed: 134 | Elapsed: 15.9 minutes

$MRC.KL: No data found, symbol may be delisted
$MRDIY.KL: No data found, symbol may be delisted
$MRL.NS: No data found, symbol may be delisted
$MSGB.KL: No data found, symbol may be delisted

Processed 1,650/2,073 | Successful: 1,512 | Failed: 138 | Elapsed: 16.4 minutes

$MTTSL.KL: No data found, symbol may be delisted
$MULTIX.SN: No data found, symbol may be delisted
$MWC.PS: No data found, symbol may be delisted
$MYNLD.PS: No data found, symbol may be delisted

Processed 1,700/2,073 | Successful: 1,558 | Failed: 142 | Elapsed: 16.9 minutes

$NADEC.SR: No data found, symbol may be delisted
$NAHDI.SR: No data found, symbol may be delisted
$NAQI.SR: No data found, symbol may be delisted
$NATGATE.KL: No data found, symbol may be delisted
$NAYIFAT.SR: No data found, symbol may be delisted
$NCLE.SR: No data found, symbol may be delisted

Processed 1,750/2,073 | Successful: 1,602 | Failed: 148 | Elapsed: 17.4 minutes

$NESZ.KL: No data found, symbol may be delisted
$NETLINK.SI: No data found, symbol may be delisted
$NGIC.SR: No data found, symbol may be delisted

Processed 1,800/2,073 | Successful: 1,649 | Failed: 151 | Elapsed: 17.9 minutes

$NIC.SR: No data found, symbol may be delisted
$NICEONE.SR: No data found, symbol may be delisted
$NIKL.PS: No data found, symbol may be delisted
$NMDC.AE: No data found, symbol may be delisted
$NMDCENR.AE: No data found, symbol may be delisted
$NORTHCEM.SR: No data found, symbol may be delisted

Processed 1,850/2,073 | Successful: 1,693 | Failed: 157 | Elapsed: 18.5 minutes

$NSCSA.SR: No data found, symbol may be delisted
$NTTDCR.SI: No data found, symbol may be delisted

Processed 1,900/2,073 | Successful: 1,741 | Failed: 159 | Elapsed: 18.9 minutes
Processed 1,950/2,073 | Successful: 1,791 | Failed: 159 | Elapsed: 19.3 minutes

$OGP.PS: No data found, symbol may be delisted
$OLG.SI: No data found, symbol may be delisted

Processed 2,000/2,073 | Successful: 1,839 | Failed: 161 | Elapsed: 19.7 minutes

$ORH.KL: No data found, symbol may be delisted
$OSK.KL: No data found, symbol may be delisted

Processed 2,050/2,073 | Successful: 1,887 | Failed: 163 | Elapsed: 20.1 minutes

$OUEREIT.SI: No data found, symbol may be delisted

Processed 2,073/2,073 | Successful: 1,909 | Failed: 164 | Elapsed: 20.3 minutes

Batch 4 complete.
Price data saved: data\price_data\batch4_prices.parquet
Failed ticker list saved: data\price_data\batch4_failed_tickers.csv
Tickers with price data: 1,909
Failed tickers: 164
Trading dates: 5,469
Total elapsed time: 20.3 minutes

In [22]:
batch5_prices, batch5_failed = download_batch(5)

Starting Batch 5: 2,073 tickers

$PAD.KL: No data found, symbol may be delisted
$PAG.NS: No data found, symbol may be delisted
$PCHEM.KL: No data found, symbol may be delisted
$PCPG.SI: No data found, symbol may be delisted

Processed 50/2,073 | Successful: 46 | Failed: 4 | Elapsed: 0.5 minutes

$PENT.KL: No data found, symbol may be delisted
$PEP.KL: No data found, symbol may be delisted
$PETD.KL: No data found, symbol may be delisted
$PETROR.SR: No data found, symbol may be delisted
$PFGRUPOA.CL: No data found, symbol may be delisted
$PFGRUPSU.CL: No data found, symbol may be delisted

Processed 100/2,073 | Successful: 90 | Failed: 10 | Elapsed: 1.0 minutes

$PG.NS: No data found, symbol may be delisted
$PGOLD.PS: No data found, symbol may be delisted
$PHRM.KL: No data found, symbol may be delisted
$PHX.AE: No data found, symbol may be delisted
$PI.NS: No data found, symbol may be delisted

Processed 150/2,073 | Successful: 135 | Failed: 15 | Elapsed: 1.6 minutes

$PLUS.PS: No data found, symbol may be delisted
$PMAH.KL: No data found, symbol may be delisted
$PMBT.KL: No data found, symbol may be delisted
$PMZ-U.TO: No data found, symbol may be delisted
$PNB.PS: No data found, symbol may be delisted

Processed 200/2,073 | Successful: 180 | Failed: 20 | Elapsed: 2.1 minutes

$PREIT.KL: No data found, symbol may be delisted
$PREIT.SI: No data found, symbol may be delisted

Processed 250/2,073 | Successful: 228 | Failed: 22 | Elapsed: 2.5 minutes

$PRESIGHT.AE: No data found, symbol may be delisted
$PROP.SI: No data found, symbol may be delisted

Processed 300/2,073 | Successful: 276 | Failed: 24 | Elapsed: 3.0 minutes

$PTG.KL: No data found, symbol may be delisted
$PX.PS: No data found, symbol may be delisted
$QACCO.SR: No data found, symbol may be delisted

Processed 350/2,073 | Successful: 323 | Failed: 27 | Elapsed: 3.5 minutes

$QLG.KL: No data found, symbol may be delisted
$QUINENC.SN: No data found, symbol may be delisted
$RADIUM.KL: No data found, symbol may be delisted
$RAHH.KL: No data found, symbol may be delisted

Processed 400/2,073 | Successful: 369 | Failed: 31 | Elapsed: 3.9 minutes

$RAKPROP.AE: No data found, symbol may be delisted
$RASAN.SR: No data found, symbol may be delisted
$RCE.KL: No data found, symbol may be delisted

Processed 450/2,073 | Successful: 416 | Failed: 34 | Elapsed: 4.4 minutes

$REDSEA.SR: No data found, symbol may be delisted
$REI-U.TO: No data found, symbol may be delisted
$RESEARCH.SR: No data found, symbol may be delisted
$RETAL.SR: No data found, symbol may be delisted
$RFMD.SI: No data found, symbol may be delisted

Processed 500/2,073 | Successful: 461 | Failed: 39 | Elapsed: 4.9 minutes

$RHBBANK.KL: No data found, symbol may be delisted
$RIYADHCA.SR: No data found, symbol may be delisted
$RLC.PS: No data found, symbol may be delisted

Processed 550/2,073 | Successful: 508 | Failed: 42 | Elapsed: 5.4 minutes

$ROTH.KL: No data found, symbol may be delisted
$RSTON.SI: No data found, symbol may be delisted

Processed 600/2,073 | Successful: 556 | Failed: 44 | Elapsed: 5.8 minutes

$SABB.SR: No data found, symbol may be delisted
$SACCO.SR: No data found, symbol may be delisted
$SACO.SR: No data found, symbol may be delisted
$SADAFCO.SR: No data found, symbol may be delisted

Processed 650/2,073 | Successful: 602 | Failed: 48 | Elapsed: 6.3 minutes

$SAL.SR: No data found, symbol may be delisted
$SALFACOR.SN: No data found, symbol may be delisted
$SAPTCO.SR: No data found, symbol may be delisted
$SATS.SI: No data found, symbol may be delisted
$SAUDIRE.SR: No data found, symbol may be delisted
$SAVOLA.SR: No data found, symbol may be delisted

Processed 700/2,073 | Successful: 646 | Failed: 54 | Elapsed: 6.9 minutes

$SAWCEM.SR: No data found, symbol may be delisted
$SBUS.SI: No data found, symbol may be delisted
$SCC.PS: No data found, symbol may be delisted
$SCERCO.SR: No data found, symbol may be delisted
$SCGB.KL: No data found, symbol may be delisted
$SCGBHD.KL: No data found, symbol may be delisted
$SCHN.NS: No data found, symbol may be delisted
$SCI.KL: No data found, symbol may be delisted
$SCI.SI: No data found, symbol may be delisted

Processed 750/2,073 | Successful: 687 | Failed: 63 | Elapsed: 7.5 minutes

$SDG.KL: No data found, symbol may be delisted
$SDPR.KL: No data found, symbol may be delisted
$SECB.PS: No data found, symbol may be delisted
$SECO.SR: No data found, symbol may be delisted
$SEERA.SR: No data found, symbol may be delisted
$SEQB.KL: No data found, symbol may be delisted
$SERT.SI: No data found, symbol may be delisted

Processed 800/2,073 | Successful: 730 | Failed: 70 | Elapsed: 8.0 minutes

$SF.NS: No data found, symbol may be delisted
$SGP.PS: No data found, symbol may be delisted
$SGREIT.SI: No data found, symbol may be delisted
$SGS.SR: No data found, symbol may be delisted

Processed 850/2,073 | Successful: 776 | Failed: 74 | Elapsed: 8.5 minutes

$SHL.SR: No data found, symbol may be delisted
$SHOP.NS: No data found, symbol may be delisted
$SIA.SI: No data found, symbol may be delisted
$SIB.AE: No data found, symbol may be delisted
$SIB.NS: No data found, symbol may be delisted
$SIBC.SR: No data found, symbol may be delisted
$SIE.SI: No data found, symbol may be delisted
$SII.NS: No data found, symbol may be delisted
$SIIG.SR: No data found, symbol may be delisted
$SIME.KL: No data found, symbol may be delisted
$SIPCHEM.SR: No data found, symbol may be delisted

Processed 900/2,073 | Successful: 815 | Failed: 85 | Elapsed: 9.2 minutes

$SISCO.SR: No data found, symbol may be delisted

Processed 950/2,073 | Successful: 864 | Failed: 86 | Elapsed: 9.6 minutes

$SM.PS: No data found, symbol may be delisted
$SMASCO.SR: No data found, symbol may be delisted
$SMCHEALT.SR: No data found, symbol may be delisted
$SMELT.KL: No data found, symbol may be delisted
$SMPH.PS: No data found, symbol may be delisted

Processed 1,000/2,073 | Successful: 909 | Failed: 91 | Elapsed: 10.1 minutes

$SOCCO.SR: No data found, symbol may be delisted
$SOLAR.KL: No data found, symbol may be delisted
$SOLUTION.SR: No data found, symbol may be delisted
$SOP.KL: No data found, symbol may be delisted
$SPACE42.AE: No data found, symbol may be delisted
$SPIMACO.SR: No data found, symbol may be delisted
$SPM.SR: No data found, symbol may be delisted

Processed 1,050/2,073 | Successful: 952 | Failed: 98 | Elapsed: 10.7 minutes

$SPSB.KL: No data found, symbol may be delisted
$SPTOTO.KL: No data found, symbol may be delisted
$SPZ.KL: No data found, symbol may be delisted
$SRE.SR: No data found, symbol may be delisted
$SRECO.SR: No data found, symbol may be delisted
$SREIT.KL: No data found, symbol may be delisted
$SRU-U.TO: No data found, symbol may be delisted
$SSB8.KL: No data found, symbol may be delisted
$SSG.SI: No data found, symbol may be delisted
$SSP.SR: No data found, symbol may be delisted

Processed 1,100/2,073 | Successful: 992 | Failed: 108 | Elapsed: 11.4 minutes

$SSW.NS: No data found, symbol may be delisted
$STE.SI: No data found, symbol may be delisted
$STH.SI: No data found, symbol may be delisted
$STM.SI: No data found, symbol may be delisted
$STMB.KL: No data found, symbol may be delisted
$STR.NS: No data found, symbol may be delisted

Processed 1,150/2,073 | Successful: 1,036 | Failed: 114 | Elapsed: 11.9 minutes

$SULAIMAN.SR: No data found, symbol may be delisted
$SUNMED.KL: No data found, symbol may be delisted
$SWB.KL: No data found, symbol may be delisted

Processed 1,200/2,073 | Successful: 1,083 | Failed: 117 | Elapsed: 12.4 minutes

$T.KL: No data found, symbol may be delisted
$TADAWULG.SR: No data found, symbol may be delisted
$TAH.KL: No data found, symbol may be delisted
$TALCO.SR: No data found, symbol may be delisted
$TAMKEEN.SR: No data found, symbol may be delisted
$TANC.KL: No data found, symbol may be delisted
$TANMIAH.SR: No data found, symbol may be delisted
$TAQA.CA: No data found, symbol may be delisted

Processed 1,250/2,073 | Successful: 1,125 | Failed: 125 | Elapsed: 13.0 minutes

$TAWUNIYA.SR: No data found, symbol may be delisted
$TDC.KL: No data found, symbol may be delisted

Processed 1,300/2,073 | Successful: 1,173 | Failed: 127 | Elapsed: 13.4 minutes

$TEL.PS: No data found, symbol may be delisted

Processed 1,350/2,073 | Successful: 1,222 | Failed: 128 | Elapsed: 13.8 minutes

$THEEB.SR: No data found, symbol may be delisted
$THMY.KL: No data found, symbol may be delisted
$TLEVICPO.MX: No data found, symbol may be delisted

Processed 1,400/2,073 | Successful: 1,269 | Failed: 131 | Elapsed: 14.3 minutes

$TMG.SI: No data found, symbol may be delisted
$TMK.KL: No data found, symbol may be delisted
$TNB.KL: No data found, symbol may be delisted
$TOPG.KL: No data found, symbol may be delisted

Processed 1,450/2,073 | Successful: 1,315 | Failed: 135 | Elapsed: 14.8 minutes

$TRCB.KL: No data found, symbol may be delisted
$TRE.NS: No data found, symbol may be delisted
$TRP.NS: No data found, symbol may be delisted

Processed 1,500/2,073 | Successful: 1,362 | Failed: 138 | Elapsed: 15.3 minutes

$TSH.KL: No data found, symbol may be delisted

Processed 1,550/2,073 | Successful: 1,411 | Failed: 139 | Elapsed: 15.7 minutes

$UCHI.KL: No data found, symbol may be delisted
$UEMS.KL: No data found, symbol may be delisted
$UGAI.SI: No data found, symbol may be delisted
$UIHC.SR: No data found, symbol may be delisted

Processed 1,600/2,073 | Successful: 1,457 | Failed: 143 | Elapsed: 16.2 minutes

$UMSH.SI: No data found, symbol may be delisted
$UNI.KL: No data found, symbol may be delisted
$UOBK.SI: No data found, symbol may be delisted
$UOL.SI: No data found, symbol may be delisted
$UPL.KL: No data found, symbol may be delisted
$URC.PS: No data found, symbol may be delisted

Processed 1,650/2,073 | Successful: 1,501 | Failed: 149 | Elapsed: 16.7 minutes

$UWC.KL: No data found, symbol may be delisted
$VALU.CA: No data found, symbol may be delisted

Processed 1,700/2,073 | Successful: 1,549 | Failed: 151 | Elapsed: 17.1 minutes

$VEB.KL: No data found, symbol may be delisted
$VITL-U.TO: No data found, symbol may be delisted
$VITRO.KL: No data found, symbol may be delisted

Processed 1,750/2,073 | Successful: 1,596 | Failed: 154 | Elapsed: 17.6 minutes

$VLMRA.CA: No data found, symbol may be delisted
$VMS.SI: No data found, symbol may be delisted

Processed 1,800/2,073 | Successful: 1,644 | Failed: 156 | Elapsed: 18.0 minutes

$VST.KL: No data found, symbol may be delisted
$VST.NS: No data found, symbol may be delisted
$WAHA.AE: No data found, symbol may be delisted
$WALAA.SR: No data found, symbol may be delisted

Processed 1,850/2,073 | Successful: 1,690 | Failed: 160 | Elapsed: 18.5 minutes

$WARBABAN.KW: No data found, symbol may be delisted

Processed 1,900/2,073 | Successful: 1,739 | Failed: 161 | Elapsed: 18.9 minutes

$WIL.SI: No data found, symbol may be delisted
$WLCON.PS: No data found, symbol may be delisted
$WPRTS.KL: No data found, symbol may be delisted

Processed 1,950/2,073 | Successful: 1,786 | Failed: 164 | Elapsed: 19.3 minutes
Processed 2,000/2,073 | Successful: 1,836 | Failed: 164 | Elapsed: 19.6 minutes

$YACCO.SR: No data found, symbol may be delisted
$YAMAMAH.SR: No data found, symbol may be delisted
$YANSAB.SR: No data found, symbol may be delisted
$YLLG.SI: No data found, symbol may be delisted
$YNCCO.SR: No data found, symbol may be delisted
$YNS.KL: No data found, symbol may be delisted
$YTL.KL: No data found, symbol may be delisted
$YTLP.KL: No data found, symbol may be delisted
$YTLREIT.KL: No data found, symbol may be delisted
$YZJSGD.SI: No data found, symbol may be delisted
$Z.NS: No data found, symbol may be delisted
$ZAINKSA.SR: No data found, symbol may be delisted

Processed 2,050/2,073 | Successful: 1,874 | Failed: 176 | Elapsed: 20.3 minutes

$ZETRIX.KL: No data found, symbol may be delisted
$ZIIC.SR: No data found, symbol may be delisted
$ZOUJAJ.SR: No data found, symbol may be delisted

Processed 2,073/2,073 | Successful: 1,894 | Failed: 179 | Elapsed: 20.6 minutes

Batch 5 complete.
Price data saved: data\price_data\batch5_prices.parquet
Failed ticker list saved: data\price_data\batch5_failed_tickers.csv
Tickers with price data: 1,894
Failed tickers: 179
Trading dates: 5,885
Total elapsed time: 20.6 minutes

In [23]:
# Load Batch 3 price data
batch3_prices = pd.read_parquet("data/price_data/batch3_prices.parquet")

# Get the 200th ticker from the Parquet columns
ticker = batch3_prices.columns[199]

print("Ticker:", ticker)
print(batch3_prices[ticker].dropna())

Ticker: AMAGI.NS
Date
2026-01-20 18:30:00+00:00    348.250000
2026-01-21 18:30:00+00:00    365.600006
2026-01-22 18:30:00+00:00    375.649994
2026-01-26 18:30:00+00:00    360.100006
2026-01-27 18:30:00+00:00    366.850006
                                ...
2026-10-04 18:30:00+00:00    569.700012
2026-10-05 18:30:00+00:00    564.150024
2026-10-06 18:30:00+00:00    561.450012
2026-10-07 18:30:00+00:00    555.299988
2026-10-08 18:30:00+00:00    559.400024
Name: AMAGI.NS, Length: 177, dtype: float64

In [24]:

from pathlib import Path
import pandas as pd

# Load all five batches and count observations per ticker
observation_counts = {}

for batch_number in range(1, 6):
    path = Path(f"data/price_data/batch{batch_number}_prices.parquet")
    prices = pd.read_parquet(path)

    observation_counts.update(prices.notna().sum().to_dict())

# Count how many tickers have each history length
length_distribution = (
    pd.Series(observation_counts, name="Observations")
    .value_counts()
    .sort_index(ascending=False)
)

length_distribution.index.name = "Price observations"
length_distribution.name = "Number of tickers"

print(length_distribution.to_string())
print(f"\nTotal tickers: {len(observation_counts):,}")

Price observations
511     277
509       7
508     235
507     383
506     106
505       2
504       5
503     374
502      36
501    2243
500     313
499     230
498      41
497     647
496     151
495      14
494      19
493     598
492      28
491       1
490       6
489       1
487     993
486    2169
485     123
484       2
483       1
479       3
478       1
477       1
476       1
475     115
474       2
473       4
472       4
471       2
470       1
469       1
467       1
466       1
465       1
464       1
463       2
462       1
461       1
459       2
458       1
457       2
454       2
453       1
452       1
450       1
449       3
447       1
446       1
445       1
444       1
443       4
442       1
441       3
439       1
438       3
435       3
433       1
432       2
430       2
429       1
428       1
427     120
425       1
423       2
422       1
421       1
420       2
419       3
418       1
416      23
415       1
414       3
413       1
412       2
410       2
409       3
408       1
406       1
403       1
402       1
401       1
397       1
392       1
389       1
386       1
385       1
384       1
383       1
382       2
381       2
380       1
377       1
376       1
375       1
372       3
368       1
367       1
366       1
364       1
359       1
357       1
355       2
354       2
353       1
352       1
351       1
348       2
346       1
343       2
341       4
339       2
338       3
335       4
334       1
333       1
332       2
330       2
329       1
327       1
326       1
325       4
324       2
323       1
322       5
320       1
319       1
318       1
317       4
316       2
315       1
314       1
313       1
312       2
311       4
308       1
307       1
306       2
304       2
303       1
302       1
301       2
299       1
298       1
296       1
295       1
294       1
292       3
291       2
290       2
287       1
285       1
284       1
283       1
281       1
278       2
275       2
272       3
271       3
269       1
268       2
267       1
266       2
265       1
263       1
262       2
261       1
260       1
259       2
258       3
256       1
255       2
254       1
252       6
251       3
248       1
246       4
245       2
244       2
243       2
242       2
240       1
239       2
238       1
237       2
234       4
233       1
232       1
231       1
230       1
229       2
228       1
226       4
225       1
224       1
222       2
221       3
219       1
218       1
216       1
215       1
214       4
212       1
209       1
207       3
206       7
205       1
204       4
203       2
202       1
201       1
200       1
199       2
198       2
197       3
196       1
195       2
194       1
193       1
192       4
191       3
190       1
189       1
186       3
185       3
183       2
180       1
179       1
177       1
176       3
173       2
172       1
171       2
168       1
167       3
166       1
165       2
164       2
163       1
162       1
160       5
156       1
155       1
150       1
148       1
147       3
146       1
144       1
141       1
139       1
138       1
137       2
136       4
134       1
132       6
131       1
130       1
123       3
122       4
121       2
119       4
117       2
114       2
113       1
105       1
102       1
99        1
95        1
83        1
82        2
74        4
70        1
66        3
65        1
57        1
51        2
29        2
7         1
5         1
1         6

Total tickers: 9,714

In [9]:
print("Earliest date:", batch1_prices.index.min())
print("Latest date:", batch1_prices.index.max())
print("Number of unique dates:", batch1_prices.index.nunique())

display(batch1_prices.head())
display(batch1_prices.tail())

Earliest date: 2024-10-07 15:00:00+00:00
Latest date: 2026-10-08 22:00:00+00:00
Number of unique dates: 2041

,000001.SZ,000002.SZ,000009.SZ,000021.SZ,000027.SZ,000029.SZ,000032.SZ,000034.SZ,000039.SZ,000050.SZ,...,3545.TW,3549.T,3563.T,3563.TW,356860.KQ,3569.T,3576.TW,357780.KQ,3583.TW,358570.KQ
Date,,,,,,,,,,,,,,,,,,,,,
2024-10-07 15:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5773.334961,NaN,NaN,211250.203125,NaN,10611.206055
2024-10-07 16:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,82.335793,NaN,NaN,360.796387,NaN,NaN,12.25,NaN,494.966278,NaN
2024-10-07 21:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-08 15:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3412.554199,1482.031128,NaN,NaN,2518.221436,NaN,NaN,NaN,NaN
2024-10-08 16:00:00+00:00,10.287009,9.34,9.55002,16.866804,6.836331,13.980663,18.766617,23.360651,8.246969,8.17,...,80.802185,NaN,NaN,350.098907,NaN,NaN,11.55,NaN,487.629822,NaN

,000001.SZ,000002.SZ,000009.SZ,000021.SZ,000027.SZ,000029.SZ,000032.SZ,000034.SZ,000039.SZ,000050.SZ,...,3545.TW,3549.T,3563.T,3563.TW,356860.KQ,3569.T,3576.TW,357780.KQ,3583.TW,358570.KQ
Date,,,,,,,,,,,,,,,,,,,,,
2026-10-07 21:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-10-07 22:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-10-08 15:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4138.0,5454.0,NaN,NaN,3495.0,NaN,NaN,NaN,NaN
2026-10-08 16:00:00+00:00,11.59,4.06,7.0,32.029999,6.34,21.299999,12.64,22.25,8.43,6.23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-10-08 22:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Compare the current index with calendar dates
print("Original unique timestamps:", batch1_prices.index.nunique())
print(
    "Unique UTC calendar dates:",
    batch1_prices.index.tz_convert("UTC").date.__class__
    if False else len(set(batch1_prices.index.tz_convert("UTC").date))
)

# Show the most common timestamp times
print("\nMost common UTC times:")
display(
    pd.Series(batch1_prices.index.strftime("%H:%M:%S %Z"))
    .value_counts()
    .head(10)
)

Original unique timestamps: 2041
Unique UTC calendar dates: 622

Most common UTC times:

Date
15:00:00 UTC    517
16:00:00 UTC    516
21:00:00 UTC    501
22:00:00 UTC    297
23:00:00 UTC    210
Name: count, dtype: int64

In [11]:
# Check whether normalising timestamps to UTC dates creates duplicate dates
normalised_dates = pd.Index(
    batch1_prices.index.tz_convert("UTC").date
)

print("Rows:", len(batch1_prices))
print("Unique UTC dates:", normalised_dates.nunique())
print("Duplicate rows after date normalisation:", normalised_dates.duplicated().sum())

Rows: 2041
Unique UTC dates: 622
Duplicate rows after date normalisation: 1419

In [12]:
# Inspect timestamps for a few stocks
for ticker in batch1_prices.columns[:5]:
    prices = batch1_prices[ticker].dropna()

    print(f"\n{ticker}")
    print("Number of observations:", len(prices))
    print("First timestamps:")
    print(prices.index[:5].tolist())

000001.SZ
Number of observations: 486
First timestamps:
[Timestamp('2024-10-08 16:00:00+0000', tz='UTC'), Timestamp('2024-10-09 16:00:00+0000', tz='UTC'), Timestamp('2024-10-10 16:00:00+0000', tz='UTC'), Timestamp('2024-10-13 16:00:00+0000', tz='UTC'), Timestamp('2024-10-14 16:00:00+0000', tz='UTC')]

000002.SZ
Number of observations: 486
First timestamps:
[Timestamp('2024-10-08 16:00:00+0000', tz='UTC'), Timestamp('2024-10-09 16:00:00+0000', tz='UTC'), Timestamp('2024-10-10 16:00:00+0000', tz='UTC'), Timestamp('2024-10-13 16:00:00+0000', tz='UTC'), Timestamp('2024-10-14 16:00:00+0000', tz='UTC')]

000009.SZ
Number of observations: 486
First timestamps:
[Timestamp('2024-10-08 16:00:00+0000', tz='UTC'), Timestamp('2024-10-09 16:00:00+0000', tz='UTC'), Timestamp('2024-10-10 16:00:00+0000', tz='UTC'), Timestamp('2024-10-13 16:00:00+0000', tz='UTC'), Timestamp('2024-10-14 16:00:00+0000', tz='UTC')]

000021.SZ
Number of observations: 486
First timestamps:
[Timestamp('2024-10-08 16:00:00+0000', tz='UTC'), Timestamp('2024-10-09 16:00:00+0000', tz='UTC'), Timestamp('2024-10-10 16:00:00+0000', tz='UTC'), Timestamp('2024-10-13 16:00:00+0000', tz='UTC'), Timestamp('2024-10-14 16:00:00+0000', tz='UTC')]

000027.SZ
Number of observations: 486
First timestamps:
[Timestamp('2024-10-08 16:00:00+0000', tz='UTC'), Timestamp('2024-10-09 16:00:00+0000', tz='UTC'), Timestamp('2024-10-10 16:00:00+0000', tz='UTC'), Timestamp('2024-10-13 16:00:00+0000', tz='UTC'), Timestamp('2024-10-14 16:00:00+0000', tz='UTC')]

In [13]:
# Convert each stock's index to its UTC calendar date
price_series = []

for ticker in batch1_prices.columns:
    prices = batch1_prices[ticker].dropna().copy()

    prices.index = prices.index.normalize()

    # Check that this stock has no duplicate dates
    if prices.index.has_duplicates:
        print(f"Duplicate dates found: {ticker}")
        continue

    prices.name = ticker
    price_series.append(prices)

# Recombine all stocks using the normalised dates
batch1_prices = pd.concat(price_series, axis=1).sort_index()
batch1_prices.index.name = "Date"

print("Shape:", batch1_prices.shape)
print("First date:", batch1_prices.index.min())
print("Last date:", batch1_prices.index.max())
print("Unique dates:", batch1_prices.index.nunique())

Shape: (622, 2048)
First date: 2024-10-07 00:00:00+00:00
Last date: 2026-10-08 00:00:00+00:00
Unique dates: 622

In [14]:
# Check missing prices after aligning dates
missing = batch1_prices.isna().sum()

print("Total price observations:", batch1_prices.size)
print("Missing price observations:", batch1_prices.isna().sum().sum())
print("Percentage missing:", round(batch1_prices.isna().sum().sum()
                                   / batch1_prices.size * 100, 2), "%")

print("\nStocks with the most missing observations:")
print(missing.sort_values(ascending=False).head(10))

Total price observations: 1273856
Missing price observations: 300328
Percentage missing: 23.58 %

Stocks with the most missing observations:
2915.HK      621
0668.HK      621
0501.HK      621
0699.HK      621
0638.HK      621
0220WL.KS    593
0220W0.KS    593
3308.HK      571
2249.HK      557
1377.HK      556
dtype: int64

In [15]:
# Inspect the stocks with the most missing prices
worst_tickers = missing.sort_values(ascending=False).head(10).index

for ticker in worst_tickers:
    prices = batch1_prices[ticker].dropna()

    print(
        f"{ticker}: {len(prices)} observations | "
        f"First: {prices.index.min()} | "
        f"Last: {prices.index.max()}"
    )

2915.HK: 1 observations | First: 2026-10-08 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00
0668.HK: 1 observations | First: 2026-10-08 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00
0501.HK: 1 observations | First: 2026-10-08 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00
0699.HK: 1 observations | First: 2026-10-08 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00
0638.HK: 1 observations | First: 2026-10-08 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00
0220WL.KS: 29 observations | First: 2026-08-25 00:00:00+00:00 | Last: 2026-10-07 00:00:00+00:00
0220W0.KS: 29 observations | First: 2026-08-25 00:00:00+00:00 | Last: 2026-10-07 00:00:00+00:00
3308.HK: 51 observations | First: 2026-07-29 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00
2249.HK: 65 observations | First: 2026-07-09 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00
1377.HK: 66 observations | First: 2026-07-08 00:00:00+00:00 | Last: 2026-10-08 00:00:00+00:00

In [16]:
# Number of available observations per stock
observations = batch1_prices.notna().sum()

print("Stocks by history length:")
print(f"At least 400 observations: {(observations >= 400).sum():,}")
print(f"200–399 observations: {((observations >= 200) & (observations < 400)).sum():,}")
print(f"50–199 observations: {((observations >= 50) & (observations < 200)).sum():,}")
print(f"Fewer than 50 observations: {(observations < 50).sum():,}")

print("\nStocks with fewer than 200 observations:")
print(observations[observations < 200].sort_values().head(20))

Stocks by history length:
At least 400 observations: 1,962
200–399 observations: 44
50–199 observations: 35
Fewer than 50 observations: 7

Stocks with fewer than 200 observations:
0699.HK        1
0501.HK        1
0638.HK        1
0668.HK        1
2915.HK        1
0220W0.KS     29
0220WL.KS     29
3308.HK       51
2249.HK       65
2475.HK       66
1377.HK       66
1688.HK       74
2493.HK      105
1879.HK      114
3296.HK      117
2476.HK      119
0068.HK      121
3277.HK      121
2726.HK      132
301682.SZ    132
dtype: int64